/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.PedidoDetalle;

import DAOs.DAOPedidoDetalleImp;
import DAOs.DAOProductosImp;
import DAOs.PedidoDetalle;
import MainPrincipal.Main;
import java.awt.BorderLayout;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 52351
 */
public class mostrarPedidoDetalle extends javax.swing.JPanel {

    /**
     * Creates new form mostrarEmpaques
     */
    public mostrarPedidoDetalle() {
        initComponents();
        ContRegistro = new DAOProductosImp().contRegistros();
        ContRegistro = Math.ceil((ContRegistro / 10));
        leyenda.setVisible(false);
    }

    private double ContRegistro;
    private int cambioPagina = 1;

    public void activeEventListenerMostrarEmp() {
        MostrarDatosPedidoDetalle();
    }

    public void setMostrarPedidoDetalle(Main worksapce) {
        mainPrincipal = worksapce;
    }

    public void MostrarDatosPedidoDetalle() {
        LinkedList<PedidoDetalle> emp = new DAOPedidoDetalleImp().show(cambioPagina);
        if (ContRegistro <= 0) {
            next.setVisible(false);
            preview.setVisible(false);
            return;
        } else {
            next.setVisible(true);
            preview.setVisible(true);
            this.segmentacion.setText("Página " + cambioPagina + " de " + (int) ContRegistro + " Páginas en total");
            Object listaDatos[][] = new Object[emp.size()][13];
            this.segmentacion.setText("Página " + cambioPagina + " de " + (int) ContRegistro + " Páginas en total");
            for (int i = 0; i < emp.size(); i++) {
                listaDatos[i][0] = emp.get(i).getIdPedidoDetalle();
                listaDatos[i][1] = emp.get(i).getCantPedida();
                listaDatos[i][2] = emp.get(i).getPrecioCompra();
                listaDatos[i][3] = emp.get(i).getSubtotal();
                listaDatos[i][4] = emp.get(i).getCantRecibida();
                listaDatos[i][5] = emp.get(i).getCantRechazada();
                listaDatos[i][6] = emp.get(i).getCantAceptada();
                listaDatos[i][7] = emp.get(i).getEstatus();
                listaDatos[i][8] = emp.get(i).getIdPedido();
                listaDatos[i][9] = emp.get(i).getIdPresentacion();
            }

            DefaultTableModel modelTable = new DefaultTableModel(
                    listaDatos,
                    new Object[]{"ID", "CANTPEDIDA", "PRECIOCOMPRA",
                        "SUBTOTAL", "CANTRECIBIDA", "CANTRECHAZADA",
                        "CANTACEPTADA", "ESTATUS",
                        "PEDIDO", "PRESENTACIÓN"}) {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            this.jTableMPro.setModel(modelTable);
            this.jTableMPro.getColumnModel().getColumn(0).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(0).setMaxWidth(50);

            this.jTableMPro.getColumnModel().getColumn(1).setMinWidth(50);
            this.jTableMPro.getColumnModel().getColumn(1).setMaxWidth(350);

            this.jTableMPro.getColumnModel().getColumn(2).setMinWidth(50);
            this.jTableMPro.getColumnModel().getColumn(2).setMaxWidth(350);

            this.jTableMPro.getColumnModel().getColumn(3).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(3).setMaxWidth(200);

            this.jTableMPro.getColumnModel().getColumn(4).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(4).setMaxWidth(200);

            this.jTableMPro.getColumnModel().getColumn(5).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(5).setMaxWidth(200);

            this.jTableMPro.getColumnModel().getColumn(6).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(6).setMaxWidth(200);

            this.jTableMPro.getColumnModel().getColumn(7).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(7).setMaxWidth(200);

            this.jTableMPro.getColumnModel().getColumn(8).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(8).setMaxWidth(200);

            this.jTableMPro.getColumnModel().getColumn(9).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(9).setMaxWidth(200);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMostrarPro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMPro = new javax.swing.JTable();
        buscartxtMPedDet = new javax.swing.JTextField();
        buscarMPedDet = new javax.swing.JLabel();
        opcionesMostrarEmp = new javax.swing.JPanel();
        nuevoMPedDet = new javax.swing.JLabel();
        cancelarMPedDet = new javax.swing.JLabel();
        opcionesMostrarLab3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        segmentacion = new javax.swing.JLabel();
        preview = new javax.swing.JButton();
        next = new javax.swing.JButton();
        leyenda = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 231, 231));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true), "Mostrar productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        mainMostrarPro.setBackground(new java.awt.Color(233, 231, 231));

        jTableMPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CANTPEDIDA", "PRECCOMP", "SUBTOTAL", "CANTRECI", "CANTRECH", "CANTACEP", "IDPEDID", "IDPRES"
            }
        ));
        jTableMPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMProMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMPro);

        buscarMPedDet.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        buscarMPedDet.setForeground(new java.awt.Color(102, 102, 102));
        buscarMPedDet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/most.png"))); // NOI18N
        buscarMPedDet.setText("BUSCAR PEDIDO");
        buscarMPedDet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        buscarMPedDet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarMPedDet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMPedDetMouseClicked(evt);
            }
        });

        opcionesMostrarEmp.setBackground(new java.awt.Color(48, 45, 45));

        nuevoMPedDet.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        nuevoMPedDet.setForeground(new java.awt.Color(255, 255, 255));
        nuevoMPedDet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        nuevoMPedDet.setText("NUEVO PEDIDO DETALLE");
        nuevoMPedDet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        nuevoMPedDet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevoMPedDet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoMPedDetMouseClicked(evt);
            }
        });

        cancelarMPedDet.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        cancelarMPedDet.setForeground(new java.awt.Color(255, 255, 255));
        cancelarMPedDet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        cancelarMPedDet.setText("CANCELAR");
        cancelarMPedDet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        cancelarMPedDet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarMPedDet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMPedDetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesMostrarEmpLayout = new javax.swing.GroupLayout(opcionesMostrarEmp);
        opcionesMostrarEmp.setLayout(opcionesMostrarEmpLayout);
        opcionesMostrarEmpLayout.setHorizontalGroup(
            opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesMostrarEmpLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(nuevoMPedDet, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarMPedDet, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        opcionesMostrarEmpLayout.setVerticalGroup(
            opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarEmpLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoMPedDet)
                    .addComponent(cancelarMPedDet))
                .addGap(21, 21, 21))
        );

        opcionesMostrarLab3.setBackground(java.awt.Color.lightGray);

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Cambio pagina \"cada página contiene 10 registros.");

        segmentacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        preview.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N
        preview.setText("Anterior");
        preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewMouseClicked(evt);
            }
        });

        next.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha.png"))); // NOI18N
        next.setText("Siguiente");
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesMostrarLab3Layout = new javax.swing.GroupLayout(opcionesMostrarLab3);
        opcionesMostrarLab3.setLayout(opcionesMostrarLab3Layout);
        opcionesMostrarLab3Layout.setHorizontalGroup(
            opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                .addGroup(opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(preview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(next))
                    .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opcionesMostrarLab3Layout.setVerticalGroup(
            opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preview)
                    .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        leyenda.setBackground(new java.awt.Color(255, 0, 51));
        leyenda.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(255, 51, 51));
        leyenda.setText("No se encuentran mas registros en paginas.");

        javax.swing.GroupLayout mainMostrarProLayout = new javax.swing.GroupLayout(mainMostrarPro);
        mainMostrarPro.setLayout(mainMostrarProLayout);
        mainMostrarProLayout.setHorizontalGroup(
            mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMostrarProLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMostrarProLayout.createSequentialGroup()
                        .addGap(0, 232, Short.MAX_VALUE)
                        .addComponent(buscartxtMPedDet, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarMPedDet, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(opcionesMostrarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(mainMostrarProLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(leyenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMostrarProLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opcionesMostrarLab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        mainMostrarProLayout.setVerticalGroup(
            mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMostrarProLayout.createSequentialGroup()
                .addGroup(mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarMPedDet)
                    .addComponent(buscartxtMPedDet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcionesMostrarLab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(leyenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(opcionesMostrarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMostrarPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMostrarPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Mostrar pedidoDetalle");
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoMPedDetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMPedDetMouseClicked
        if (new DAOPedidoDetalleImp().obternerIdPedido() != null && new DAOPedidoDetalleImp().obternerIdPresentacion() != null) {
            mainPrincipal.getworkSpace().removeAll();
            agregarPedidoDetalle nuevoEmp = new agregarPedidoDetalle();
            nuevoEmp.setSize(mainPrincipal.getworkSpace().getSize());
            nuevoEmp.setVisible(true);
            nuevoEmp.setMainPrincipal(mainPrincipal);
            mainPrincipal.getworkSpace().add(nuevoEmp, BorderLayout.CENTER);
            mainPrincipal.getworkSpace().revalidate();
            mainPrincipal.getworkSpace().repaint();

        } else {
            JOptionPane.showMessageDialog(this, "Pedidos  y presentaciones no disponibles, registre por lo menos una "
                    + "pedido y presentación en el sistema", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_nuevoMPedDetMouseClicked

    private void cancelarMPedDetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMPedDetMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();
    }//GEN-LAST:event_cancelarMPedDetMouseClicked

    private void jTableMProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMProMouseClicked
        int row;
        row = jTableMPro.getSelectedRow();
        //Verificamos que el evento este en el rango de la tabla.
        if (row > -1 && row <= jTableMPro.getSelectedRow()) {
            //creamos la ventana modificar
            modificarPedidoDetalle modificarEmpaque = new modificarPedidoDetalle();
            this.mainPrincipal.getworkSpace().removeAll();
            modificarEmpaque.setSize(mainPrincipal.getworkSpace().getSize());
            modificarEmpaque.setVisible(true);
            modificarEmpaque.setMainPrincipal(mainPrincipal);
            //Datos de la tabla, selecionar un row

            int id = Integer.parseInt(String.valueOf(this.jTableMPro.getValueAt(row, 0)));
            int cantPed = Integer.parseInt(String.valueOf(this.jTableMPro.getValueAt(row, 1)));
            float precioCom = Float.parseFloat(String.valueOf(this.jTableMPro.getValueAt(row, 2)));
            float subtotal = Float.parseFloat(String.valueOf(this.jTableMPro.getValueAt(row, 3)));
            int cantReci = Integer.parseInt(String.valueOf(this.jTableMPro.getValueAt(row, 4)));
            int cantRecha = Integer.parseInt(String.valueOf(this.jTableMPro.getValueAt(row, 5)));
            float cantAcep = Float.parseFloat(String.valueOf(this.jTableMPro.getValueAt(row, 6)));
            char estatus = String.valueOf(this.jTableMPro.getValueAt(row, 7)).charAt(0);
            String pedido = String.valueOf(this.jTableMPro.getValueAt(row, 8));
            String presentacion = String.valueOf(this.jTableMPro.getValueAt(row, 9));
            //Ingresan los datos de la tabla a la interfaz Modificar Laboratorio
            modificarEmpaque.ObtenerLaboratoriModificar(new PedidoDetalle(id, cantPed, 
                        precioCom, subtotal, cantReci, cantRecha, 
                        cantAcep, estatus, pedido, presentacion));

            this.mainPrincipal.getworkSpace().add(modificarEmpaque, BorderLayout.CENTER);
            this.mainPrincipal.getworkSpace().revalidate();
            this.mainPrincipal.getworkSpace().repaint();
        }
    }//GEN-LAST:event_jTableMProMouseClicked

    private void buscarMPedDetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMPedDetMouseClicked
        if (buscartxtMPedDet.getText() == "" || buscartxtMPedDet.getText() == null) {
            JOptionPane.showMessageDialog(null, "Debes escribir algo para filtrar...",
                    "Mensaje", JOptionPane.WARNING_MESSAGE);
        } else {
            LinkedList<PedidoDetalle> cat = new DAOPedidoDetalleImp().consultaInd(buscartxtMPedDet.getText());
            Object listaDatos[][] = new Object[cat.size()][10];
            for (int i = 0; i < cat.size(); i++) {
                listaDatos[i][0] = cat.get(i).getIdPedido();
                listaDatos[i][1] = cat.get(i).getCantPedida();
                listaDatos[i][2] = cat.get(i).getPrecioCompra();
                listaDatos[i][3] = cat.get(i).getSubtotal();
                listaDatos[i][4] = cat.get(i).getCantRecibida();
                listaDatos[i][5] = cat.get(i).getCantRechazada();
                listaDatos[i][6] = cat.get(i).getCantAceptada();
                listaDatos[i][7] = cat.get(i).getEstatus();
                listaDatos[i][8] = cat.get(i).getIdPedido();
                listaDatos[i][9] = cat.get(i).getIdPresentacion();
            }

            DefaultTableModel modelTable = new DefaultTableModel(
                    listaDatos,
                    new Object[]{"ID", "CANTPEDIDA", "PRECIOCOMPRA",
                        "SUBTOTAL", "CANTRECIBIDA", "CANTRECHAZADA",
                        "CANTACEPTADA", "ESTATUS",
                        "PEDIDO", "PRESENTACIÓN"}) {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            this.jTableMPro.setModel(modelTable);
            this.jTableMPro.getColumnModel().getColumn(0).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(0).setMaxWidth(50);

            this.jTableMPro.getColumnModel().getColumn(1).setMinWidth(50);
            this.jTableMPro.getColumnModel().getColumn(1).setMaxWidth(350);

            this.jTableMPro.getColumnModel().getColumn(2).setMinWidth(50);
            this.jTableMPro.getColumnModel().getColumn(2).setMaxWidth(350);

            this.jTableMPro.getColumnModel().getColumn(3).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(3).setMaxWidth(200);

            this.jTableMPro.getColumnModel().getColumn(4).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(4).setMaxWidth(200);

            this.jTableMPro.getColumnModel().getColumn(5).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(5).setMaxWidth(200);

            this.jTableMPro.getColumnModel().getColumn(6).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(6).setMaxWidth(200);

            this.jTableMPro.getColumnModel().getColumn(7).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(7).setMaxWidth(200);

            this.jTableMPro.getColumnModel().getColumn(8).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(8).setMaxWidth(200);

            this.jTableMPro.getColumnModel().getColumn(9).setMinWidth(10);
            this.jTableMPro.getColumnModel().getColumn(9).setMaxWidth(200);


        }

    }//GEN-LAST:event_buscarMPedDetMouseClicked

    private void previewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewMouseClicked
        if (cambioPagina == 1) {
            preview.setVisible(false);
            next.setVisible(true);
            leyenda.setVisible(true);
            MostrarDatosPedidoDetalle();
        } else {
            next.setVisible(true);
            cambioPagina--;
            MostrarDatosPedidoDetalle();
            leyenda.setVisible(false);

        }
    }//GEN-LAST:event_previewMouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        if (cambioPagina >= ContRegistro) {
            next.setVisible(false);
            preview.setVisible(true);
            leyenda.setVisible(true);
            MostrarDatosPedidoDetalle();
        } else {
            cambioPagina++;
            preview.setVisible(true);
            MostrarDatosPedidoDetalle();
            leyenda.setVisible(false);
        }
    }//GEN-LAST:event_nextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarMPedDet;
    private javax.swing.JTextField buscartxtMPedDet;
    private javax.swing.JLabel cancelarMPedDet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMPro;
    private javax.swing.JLabel leyenda;
    private javax.swing.JPanel mainMostrarPro;
    private javax.swing.JButton next;
    private javax.swing.JLabel nuevoMPedDet;
    private javax.swing.JPanel opcionesMostrarEmp;
    private javax.swing.JPanel opcionesMostrarLab3;
    private javax.swing.JButton preview;
    private javax.swing.JLabel segmentacion;
    // End of variables declaration//GEN-END:variables
    private Main mainPrincipal;

}
