/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.ProductosProveedor;

import Vistas.ProductosProveedor.*;
import DAOs.DAOProductoProveedorImp;
import DAOs.DAOProductoProveedor;
import DAOs.Presentaciones;
import DAOs.ProductoProveedor;
import java.awt.BorderLayout;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import MainPrincipal.Main;

/**
 *
 * @author 52351
 */
public class agregarProductosProveedor extends javax.swing.JPanel {

    /**
     * Creates new form agregarEmpaque
     */
    public agregarProductosProveedor() {
        initComponents();
        mostrarProveedor();
        mostrarPresentacion();
    }

    private void mostrarProveedor() {
        LinkedList<ProductoProveedor> proveedor = new DAOProductoProveedorImp().obtenerIdProveedor();
        if (proveedor != null) {
            DefaultComboBoxModel model = (DefaultComboBoxModel) comboxProveedor.getModel();
            for (int i = 0; i < proveedor.size(); i++) {
                model.addElement(proveedor.get(i).getIdProveedor());
            }
            comboxProveedor.setModel(model);
        }
    }

    private void mostrarPresentacion() {
        LinkedList<ProductoProveedor> productos = new DAOProductoProveedorImp().obtenerIdProducto();
        if (productos != null) {
            DefaultComboBoxModel model2 = (DefaultComboBoxModel) comboxPresentacion.getModel();
            for (int i = 0; i < productos.size(); i++) {
                model2.addElement(productos.get(i).getIdProductos());
            }
            comboxPresentacion.setModel(model2);
        }
    }

    private Main mainPrincipal;

    public void setMainPrincipal(Main main) {
        mainPrincipal = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCompras = new javax.swing.JLabel();
        precioVentas = new javax.swing.JLabel();
        precioUltimaCompra = new javax.swing.JTextField();
        opcionesAEmp = new javax.swing.JPanel();
        cancelarAEmp = new javax.swing.JLabel();
        guardarAEmp = new javax.swing.JLabel();
        prodcutos = new javax.swing.JLabel();
        comboxPresentacion = new javax.swing.JComboBox();
        puntoReordenn = new javax.swing.JLabel();
        diaRetardo = new javax.swing.JTextField();
        empaques = new javax.swing.JLabel();
        comboxProveedor = new javax.swing.JComboBox();
        pCompras1 = new javax.swing.JLabel();
        pCompras2 = new javax.swing.JLabel();
        cantidadMaxPedir = new javax.swing.JTextField();
        cantidadMinimaPedir = new javax.swing.JTextField();
        precioEstandar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(228, 225, 225));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true), "Agregar nueva Presentacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        pCompras.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pCompras.setText("PRECIO ULTIMA COMPRA: ");

        precioVentas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        precioVentas.setText("DÍA RETARDO: ");

        precioUltimaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioUltimaCompraActionPerformed(evt);
            }
        });

        opcionesAEmp.setBackground(new java.awt.Color(48, 45, 45));

        cancelarAEmp.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        cancelarAEmp.setForeground(new java.awt.Color(255, 255, 255));
        cancelarAEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        cancelarAEmp.setText("CANCELAR");
        cancelarAEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        cancelarAEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarAEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarAEmpMouseClicked(evt);
            }
        });

        guardarAEmp.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        guardarAEmp.setForeground(new java.awt.Color(255, 255, 255));
        guardarAEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        guardarAEmp.setText("GUARDAR ");
        guardarAEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        guardarAEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarAEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarAEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarAEmpMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout opcionesAEmpLayout = new javax.swing.GroupLayout(opcionesAEmp);
        opcionesAEmp.setLayout(opcionesAEmpLayout);
        opcionesAEmpLayout.setHorizontalGroup(
            opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesAEmpLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(guardarAEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(cancelarAEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        opcionesAEmpLayout.setVerticalGroup(
            opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesAEmpLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarAEmp)
                    .addComponent(guardarAEmp))
                .addGap(45, 45, 45))
        );

        prodcutos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        prodcutos.setText("PRESENTACIÓN:");

        comboxPresentacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboxPresentacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONA UN PRODUCTO" }));

        puntoReordenn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        puntoReordenn.setText("PRECIO ESTANDAR: ");

        empaques.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        empaques.setText("PROVEEDOR: ");

        comboxProveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboxProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONA UN PROVEEDOR" }));

        pCompras1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pCompras1.setText("CANTIDAD MIXIMA PEDIR:");

        pCompras2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pCompras2.setText("CANTIDAD MINIMA PEDIR:");

        cantidadMaxPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMaxPedirActionPerformed(evt);
            }
        });

        cantidadMinimaPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMinimaPedirActionPerformed(evt);
            }
        });

        precioEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioEstandarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcionesAEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodcutos)
                    .addComponent(pCompras)
                    .addComponent(precioVentas)
                    .addComponent(puntoReordenn)
                    .addComponent(empaques)
                    .addComponent(pCompras2)
                    .addComponent(pCompras1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(diaRetardo)
                    .addComponent(comboxPresentacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboxProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precioUltimaCompra)
                    .addComponent(cantidadMaxPedir)
                    .addComponent(cantidadMinimaPedir)
                    .addComponent(precioEstandar))
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empaques)
                    .addComponent(comboxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodcutos)
                    .addComponent(comboxPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioVentas)
                    .addComponent(diaRetardo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puntoReordenn)
                    .addComponent(precioEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pCompras)
                    .addComponent(precioUltimaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pCompras2)
                    .addComponent(cantidadMinimaPedir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pCompras1)
                    .addComponent(cantidadMaxPedir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(opcionesAEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarAEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarAEmpMouseClicked
        try {
            if (comboxProveedor.getSelectedIndex() <= 0) {
                comboxProveedor.requestFocus();
                JOptionPane.showMessageDialog(this, "Seleccione algun proveedor\n, en caso de no tener uno, debe registrar un proveedor", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if (comboxPresentacion.getSelectedIndex() <= 0) {
                comboxPresentacion.requestFocus();
                JOptionPane.showMessageDialog(this, "Seleccione un producto\n, en caso de no tener uno, debe registrar un producto", "ERROR", JOptionPane.ERROR_MESSAGE);
            }  else if (diaRetardo.getText().equals("") || Integer.parseInt(diaRetardo.getText()) <= 0) {
                diaRetardo.requestFocus();
                JOptionPane.showMessageDialog(this, "Ingrese un punto de reorden", "ERROR", JOptionPane.ERROR_MESSAGE);
            }  else if (precioEstandar.getText().equals("") || Float.parseFloat(precioEstandar.getText()) <= 0) {
                precioEstandar.requestFocus();
                JOptionPane.showMessageDialog(this, "Ingrese un precio de compra", "ERROR", JOptionPane.ERROR_MESSAGE);
            }else if (precioUltimaCompra.getText().equals("") || Float.parseFloat(precioUltimaCompra.getText()) <= 0) {
                precioUltimaCompra.requestFocus();
                JOptionPane.showMessageDialog(this, "Ingrese un precio de compra", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if ((cantidadMinimaPedir.getText().equals("") || Float.parseFloat(cantidadMinimaPedir.getText()) <= 0)
                    &&(Integer.parseInt(cantidadMinimaPedir.getText())>Integer.parseInt(cantidadMaxPedir.getText())) ) {
                cantidadMinimaPedir.requestFocus();
                JOptionPane.showMessageDialog(this, "Seleccione la cantidad de producto, debe ser mayor a 0", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if ((cantidadMaxPedir.getText().equals("") || Float.parseFloat(cantidadMaxPedir.getText())<= 0 )
                    &&(Integer.parseInt(cantidadMaxPedir.getText())<Integer.parseInt(cantidadMinimaPedir.getText()))) {
                cantidadMaxPedir.requestFocus();
                JOptionPane.showMessageDialog(this, "Seleccione la cantidad de producto, debe ser no mayor a la existencia", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    String idProveedor = comboxProveedor.getSelectedItem().toString();
                    String presentacion = comboxPresentacion.getSelectedItem().toString();
                    int diasRetardo = Integer.parseInt(diaRetardo.getText());
                    float precioEstandar = Float.parseFloat(this.precioEstandar.getText());
                    float ultimoPrecio = Float.parseFloat(this.precioUltimaCompra.getText());
                    int cantMinPedir = Integer.parseInt(cantidadMinimaPedir.getText());
                    int cantMaxPedir = Integer.parseInt(this.cantidadMaxPedir.getText());
                   // new DAOProductoProveedorImp().Insert(new ProductoProveedor(TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY, null, TOP_ALIGNMENT, TOP_ALIGNMENT, SOMEBITS, SOMEBITS, estatus));
                    new DAOProductoProveedorImp().Insert(new ProductoProveedor
                    (idProveedor,presentacion,diasRetardo,precioEstandar,ultimoPrecio,cantMinPedir,cantMaxPedir));
                    limpiarVariables();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, " solo numeros", "Error de tipo de dato", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Capacidad solo numeros", "Error de tipo de dato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarAEmpMouseClicked

    private void cancelarAEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarAEmpMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        mostrarProductosProveedor mostrarProdProvee = new mostrarProductosProveedor();
        mostrarProdProvee.setSize(mainPrincipal.getworkSpace().getSize());
        mostrarProdProvee.setVisible(true);
        mostrarProdProvee.setMostrarProductosProveedores(mainPrincipal);
        mostrarProdProvee.MostrarDatosProdProveedor();
        mainPrincipal.getworkSpace().add(mostrarProdProvee, BorderLayout.CENTER);
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();

    }//GEN-LAST:event_cancelarAEmpMouseClicked

    private void limpiarVariables() {
        comboxProveedor.setSelectedIndex(0);
        comboxPresentacion.setSelectedIndex(0);
        diaRetardo.setText("");
        precioUltimaCompra.setText("");
        diaRetardo.setText("");
        cantidadMinimaPedir.setText("");
        cantidadMaxPedir.setText("");

    }

    private void guardarAEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarAEmpMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarAEmpMouseEntered

    private void precioUltimaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioUltimaCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioUltimaCompraActionPerformed

    private void cantidadMaxPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMaxPedirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadMaxPedirActionPerformed

    private void cantidadMinimaPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMinimaPedirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadMinimaPedirActionPerformed

    private void precioEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioEstandarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioEstandarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelarAEmp;
    private javax.swing.JTextField cantidadMaxPedir;
    private javax.swing.JTextField cantidadMinimaPedir;
    private javax.swing.JComboBox comboxPresentacion;
    private javax.swing.JComboBox comboxProveedor;
    private javax.swing.JTextField diaRetardo;
    private javax.swing.JLabel empaques;
    private javax.swing.JLabel guardarAEmp;
    private javax.swing.JPanel opcionesAEmp;
    private javax.swing.JLabel pCompras;
    private javax.swing.JLabel pCompras1;
    private javax.swing.JLabel pCompras2;
    private javax.swing.JTextField precioEstandar;
    private javax.swing.JTextField precioUltimaCompra;
    private javax.swing.JLabel precioVentas;
    private javax.swing.JLabel prodcutos;
    private javax.swing.JLabel puntoReordenn;
    // End of variables declaration//GEN-END:variables

}
