/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.ProductosProveedor;

import Vistas.ProductosProveedor.*;
import ClasesExtras.CRUDgenerico;
import DAOs.DAOProductoProveedor;
import DAOs.DAOProductoProveedorImp;
import DAOs.ProductoProveedor;
import MainPrincipal.Main;
import java.awt.BorderLayout;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 52351
 */
public class mostrarProductosProveedor extends javax.swing.JPanel {

    /**
     * Creates new form mostrarEmpaques
     */
    public mostrarProductosProveedor() {
        initComponents();
        ContRegistro = new DAOProductoProveedorImp().contRegistro();
        ContRegistro = Math.ceil((ContRegistro/10));
        leyenda.setVisible(false);
    }

    private double ContRegistro;
    private int cambioPagina = 1;

    public void activeEventListenerMostrarPresProv() {
        MostrarDatosProdProv();
    }

    public void setMostrarProdProv(Main worksapce) {
        mainPrincipal = worksapce;
    }

    public void MostrarDatosProdProv() {
        LinkedList<ProductoProveedor> pProv = new DAOProductoProveedorImp().show(1);
        Object listaDatos[][] = new Object[pProv.size()][8];
         this.segmentacion.setText("Página "+cambioPagina +" de "+ (int)ContRegistro+ " Páginas en total");
        for (int i = 0; i < pProv.size(); i++) {
            listaDatos[i][0] = pProv.get(i).getIdProveedor();
            listaDatos[i][1] = pProv.get(i).getIdPresentaciones();
            listaDatos[i][2] = pProv.get(i).getDiasRetardo();
            listaDatos[i][3] = pProv.get(i).getPrecioEstandar();
            listaDatos[i][4] = pProv.get(i).getPrecioUltCompra();
            listaDatos[i][5] = pProv.get(i).getCantMinPedir();
            listaDatos[i][6] = pProv.get(i).getCantMaxPedir();
            listaDatos[i][7] = pProv.get(i).getEstatus();
        }

        DefaultTableModel modelTable = new DefaultTableModel(
                listaDatos,
                new Object[]{"PROVEEDORES", "PRESENTACION", "DIAS RETRASO",
                        "PRECIO ESTANDAR", "PRECIO ULTIMA COMPRA", "CANT. MIN. PEDIR",
                        "CANT. MIN. PEDIR", "ESTATUS"}) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        this.jTableMEmp.setModel(modelTable);
        this.jTableMEmp.getColumnModel().getColumn(0).setMinWidth(10);
        this.jTableMEmp.getColumnModel().getColumn(0).setMaxWidth(50);

        this.jTableMEmp.getColumnModel().getColumn(1).setMinWidth(50);
        this.jTableMEmp.getColumnModel().getColumn(1).setMaxWidth(350);

        this.jTableMEmp.getColumnModel().getColumn(2).setMinWidth(50);
        this.jTableMEmp.getColumnModel().getColumn(2).setMaxWidth(350);

        this.jTableMEmp.getColumnModel().getColumn(3).setMinWidth(10);
        this.jTableMEmp.getColumnModel().getColumn(3).setMaxWidth(200);

        this.jTableMEmp.getColumnModel().getColumn(4).setMinWidth(10);
        this.jTableMEmp.getColumnModel().getColumn(4).setMaxWidth(200);

        this.jTableMEmp.getColumnModel().getColumn(5).setMinWidth(10);
        this.jTableMEmp.getColumnModel().getColumn(5).setMaxWidth(200);

        this.jTableMEmp.getColumnModel().getColumn(6).setMinWidth(10);
        this.jTableMEmp.getColumnModel().getColumn(6).setMaxWidth(200);

        this.jTableMEmp.getColumnModel().getColumn(7).setMinWidth(10);
        this.jTableMEmp.getColumnModel().getColumn(7).setMaxWidth(200);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMostrarEmp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMEmp = new javax.swing.JTable();
        buscartxtMEmp = new javax.swing.JTextField();
        buscarMEmp = new javax.swing.JLabel();
        opcionesMostrarEmp = new javax.swing.JPanel();
        nuevoMEmp = new javax.swing.JLabel();
        cancelarMEmp = new javax.swing.JLabel();
        opcionesMostrarLab3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        segmentacion = new javax.swing.JLabel();
        preview = new javax.swing.JButton();
        next = new javax.swing.JButton();
        leyenda = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 231, 231));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true), "Mostrar Productos Proveedor ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        mainMostrarEmp.setBackground(new java.awt.Color(233, 231, 231));

        jTableMEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PROVEEDOR", "PRESENTACIÓN", "DIAS RETRASO", "PRECIO ESTANDAR", "PRECIO ULTIMA COMPRA", "CANT. MIN. PEDIR", "CANT. MAX. PEDIR", "ESTATUS"
            }
        ));
        jTableMEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMEmp);

        buscarMEmp.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        buscarMEmp.setForeground(new java.awt.Color(102, 102, 102));
        buscarMEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/most.png"))); // NOI18N
        buscarMEmp.setText("BUSCAR PRODUCTO PROVEEDOR");
        buscarMEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        buscarMEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarMEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMEmpMouseClicked(evt);
            }
        });

        opcionesMostrarEmp.setBackground(new java.awt.Color(48, 45, 45));

        nuevoMEmp.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        nuevoMEmp.setForeground(new java.awt.Color(255, 255, 255));
        nuevoMEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        nuevoMEmp.setText("NUEVO PRODUCTO PROVEEDPOR");
        nuevoMEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        nuevoMEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevoMEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoMEmpMouseClicked(evt);
            }
        });

        cancelarMEmp.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        cancelarMEmp.setForeground(new java.awt.Color(255, 255, 255));
        cancelarMEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        cancelarMEmp.setText("CANCELAR");
        cancelarMEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        cancelarMEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarMEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMEmpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesMostrarEmpLayout = new javax.swing.GroupLayout(opcionesMostrarEmp);
        opcionesMostrarEmp.setLayout(opcionesMostrarEmpLayout);
        opcionesMostrarEmpLayout.setHorizontalGroup(
            opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesMostrarEmpLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(nuevoMEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarMEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        opcionesMostrarEmpLayout.setVerticalGroup(
            opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarEmpLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoMEmp)
                    .addComponent(cancelarMEmp))
                .addGap(21, 21, 21))
        );

        opcionesMostrarLab3.setBackground(java.awt.Color.lightGray);

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Cambio pagina \"cada página contiene 10 registros.");

        segmentacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        preview.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N
        preview.setText("Anterior");
        preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewMouseClicked(evt);
            }
        });

        next.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha.png"))); // NOI18N
        next.setText("Siguiente");
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesMostrarLab3Layout = new javax.swing.GroupLayout(opcionesMostrarLab3);
        opcionesMostrarLab3.setLayout(opcionesMostrarLab3Layout);
        opcionesMostrarLab3Layout.setHorizontalGroup(
            opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                .addGroup(opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(preview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(next))
                    .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opcionesMostrarLab3Layout.setVerticalGroup(
            opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preview)
                    .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        leyenda.setBackground(new java.awt.Color(255, 0, 51));
        leyenda.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(255, 51, 51));
        leyenda.setText("No se encuentran mas registros en paginas.");

        javax.swing.GroupLayout mainMostrarEmpLayout = new javax.swing.GroupLayout(mainMostrarEmp);
        mainMostrarEmp.setLayout(mainMostrarEmpLayout);
        mainMostrarEmpLayout.setHorizontalGroup(
            mainMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMostrarEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMostrarEmpLayout.createSequentialGroup()
                        .addGap(0, 232, Short.MAX_VALUE)
                        .addComponent(buscartxtMEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarMEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(opcionesMostrarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(mainMostrarEmpLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(leyenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMostrarEmpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opcionesMostrarLab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        mainMostrarEmpLayout.setVerticalGroup(
            mainMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMostrarEmpLayout.createSequentialGroup()
                .addGroup(mainMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarMEmp)
                    .addComponent(buscartxtMEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcionesMostrarLab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(leyenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(opcionesMostrarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMostrarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMostrarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoMEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMEmpMouseClicked
            mainPrincipal.getworkSpace().removeAll();
            agregarProductosProveedor nuevoProdProv = new agregarProductosProveedor();
            nuevoProdProv.setSize(mainPrincipal.getworkSpace().getSize());
            nuevoProdProv.setVisible(true);
            nuevoProdProv.setMainPrincipal(mainPrincipal);
            mainPrincipal.getworkSpace().add(nuevoProdProv, BorderLayout.CENTER);
            mainPrincipal.getworkSpace().revalidate();
            mainPrincipal.getworkSpace().repaint();
      
    }//GEN-LAST:event_nuevoMEmpMouseClicked

    private void cancelarMEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMEmpMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();
    }//GEN-LAST:event_cancelarMEmpMouseClicked

    private void jTableMEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMEmpMouseClicked
        int row;
        row = jTableMEmp.getSelectedRow();
        //Verificamos que el evento este en el rango de la tabla.
        if (row > -1 && row <= jTableMEmp.getSelectedRow()) {
            //creamos la ventana modificar
            modificarProductosProveedor modificarProdProv = new modificarProductosProveedor();
            this.mainPrincipal.getworkSpace().removeAll();
            modificarProdProv.setSize(mainPrincipal.getworkSpace().getSize());
            modificarProdProv.setVisible(true);
            modificarProdProv.setMainPrincipal(mainPrincipal);
            //Datos de la tabla, selecionar un row
            String prov = String.valueOf(this.jTableMEmp.getValueAt(row, 0));
            String pres = String.valueOf(this.jTableMEmp.getValueAt(row, 1));
            int dRetardo = Integer.parseInt(String.valueOf(this.jTableMEmp.getValueAt(row, 2)));
            float pEstandar = Float.parseFloat(String.valueOf(this.jTableMEmp.getValueAt(row, 3)));
            float pUltCompra = Float.parseFloat(String.valueOf(this.jTableMEmp.getValueAt(row, 4)));
            int cMinPedir = Integer.parseInt(String.valueOf(this.jTableMEmp.getValueAt(row, 5)));
            int cMaxPedir = Integer.parseInt(String.valueOf(this.jTableMEmp.getValueAt(row, 6)));
            char estatus = String.valueOf(this.jTableMEmp.getValueAt(row, 7)).charAt(0);
            //Ingresan los datos de la tabla a la interfaz Modificar Laboratorio
            modificarProdProv.ObtenerProdProvModificar(new ProductoProveedor(prov, pres, dRetardo, pEstandar, pUltCompra, cMinPedir, cMaxPedir,estatus));

            this.mainPrincipal.getworkSpace().add(modificarProdProv, BorderLayout.CENTER);
            this.mainPrincipal.getworkSpace().revalidate();
            this.mainPrincipal.getworkSpace().repaint();
        }
    }//GEN-LAST:event_jTableMEmpMouseClicked

    private void buscarMEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMEmpMouseClicked
        LinkedList<ProductoProveedor> pProv = new DAOProductoProveedorImp().busquedaPorNombre(Integer.parseInt(buscartxtMEmp.getText()));
        this.segmentacion.setText("Página "+cambioPagina +" de "+ (int)ContRegistro+ " Páginas en total");
        Object listaDatos[][] = new Object[pProv.size()][8];
        for (int i = 0; i < pProv.size(); i++) {
            listaDatos[i][0] = pProv.get(i).getIdProveedor();
            listaDatos[i][1] = pProv.get(i).getIdPresentaciones();
            listaDatos[i][2] = pProv.get(i).getDiasRetardo();
            listaDatos[i][3] = pProv.get(i).getPrecioEstandar();
            listaDatos[i][4] = pProv.get(i).getPrecioUltCompra();
            listaDatos[i][5] = pProv.get(i).getCantMinPedir();
            listaDatos[i][6] = pProv.get(i).getCantMaxPedir();
            listaDatos[i][7] = pProv.get(i).getEstatus();
        }

        DefaultTableModel modelTable = new DefaultTableModel(
                listaDatos,
                new Object[]{"PROVEEDOR", "PRESENTACION", "DIAS RETRASO",
                    "PRECIO ESTANDAR","PRECIO ULT. COMPRA",
                    "CANT. MIN. PEDIR","CANT. MAX. PEDIR","ESTATUS"}) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        this.jTableMEmp.setModel(modelTable);
        this.jTableMEmp.getColumnModel().getColumn(0).setMinWidth(10);
        this.jTableMEmp.getColumnModel().getColumn(0).setMaxWidth(50);

        this.jTableMEmp.getColumnModel().getColumn(1).setMinWidth(50);
        this.jTableMEmp.getColumnModel().getColumn(1).setMaxWidth(350);

        this.jTableMEmp.getColumnModel().getColumn(2).setMinWidth(50);
        this.jTableMEmp.getColumnModel().getColumn(2).setMaxWidth(350);

        this.jTableMEmp.getColumnModel().getColumn(3).setMinWidth(10);
        this.jTableMEmp.getColumnModel().getColumn(3).setMaxWidth(200);

        this.jTableMEmp.getColumnModel().getColumn(4).setMinWidth(10);
        this.jTableMEmp.getColumnModel().getColumn(4).setMaxWidth(200);

        this.jTableMEmp.getColumnModel().getColumn(5).setMinWidth(10);
        this.jTableMEmp.getColumnModel().getColumn(5).setMaxWidth(200);

        this.jTableMEmp.getColumnModel().getColumn(6).setMinWidth(10);
        this.jTableMEmp.getColumnModel().getColumn(6).setMaxWidth(200);

        this.jTableMEmp.getColumnModel().getColumn(7).setMinWidth(10);
        this.jTableMEmp.getColumnModel().getColumn(7).setMaxWidth(200);

    }//GEN-LAST:event_buscarMEmpMouseClicked

    private void previewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewMouseClicked
        if (cambioPagina == 1) {
            preview.setVisible(false);
            next.setVisible(true);
            leyenda.setVisible(true);
            MostrarDatosProdProv();
        } else {
            next.setVisible(true);
            cambioPagina--;
            MostrarDatosProdProv();
            leyenda.setVisible(false);

        }
    }//GEN-LAST:event_previewMouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        if (cambioPagina >= ContRegistro) {
            next.setVisible(false);
            preview.setVisible(true);
            leyenda.setVisible(true);
            MostrarDatosProdProv();
        } else {
            cambioPagina++;
            preview.setVisible(true);
            MostrarDatosProdProv();
            leyenda.setVisible(false);
        }
    }//GEN-LAST:event_nextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarMEmp;
    private javax.swing.JTextField buscartxtMEmp;
    private javax.swing.JLabel cancelarMEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMEmp;
    private javax.swing.JLabel leyenda;
    private javax.swing.JPanel mainMostrarEmp;
    private javax.swing.JButton next;
    private javax.swing.JLabel nuevoMEmp;
    private javax.swing.JPanel opcionesMostrarEmp;
    private javax.swing.JPanel opcionesMostrarLab3;
    private javax.swing.JButton preview;
    private javax.swing.JLabel segmentacion;
    // End of variables declaration//GEN-END:variables
    private Main mainPrincipal;

}
