/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.CuentasProveedor;

import DAOs.CuentasProveedor;
import DAOs.DAOCuentaProveedorImp;
import Vistas.Presentaciones.*;
import Vistas.Empaques.*;
import DAOs.DAOEmpaquesImp;
import DAOs.DAOPresentacionesImp;
import DAOs.Empaques;
import DAOs.Presentaciones;
import java.awt.BorderLayout;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import MainPrincipal.Main;

/**
 *
 * @author 52351
 */
public class agregarCuentasProveedor extends javax.swing.JPanel {

    /**
     * Creates new form agregarEmpaque
     */
    public agregarCuentasProveedor() {
        initComponents();
        mostrarProveedor();
    }

    private void mostrarProveedor() {
        LinkedList<CuentasProveedor> cProve = new DAOCuentaProveedorImp().obtenerIdProveedores();
        if (cProve != null) {
            DefaultComboBoxModel model = (DefaultComboBoxModel) proveedorCbx.getModel();
            for (int i = 0; i < cProve.size(); i++) {
                model.addElement(cProve.get(i).getProveedor());
            }
            proveedorCbx.setModel(model);
        }
    }

    private Main mainPrincipal;

    public void setMainPrincipal(Main main) {
        mainPrincipal = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noCuenta = new javax.swing.JLabel();
        banco = new javax.swing.JLabel();
        noCuentatxt = new javax.swing.JTextField();
        bancotxt = new javax.swing.JTextField();
        opcionesAEmp = new javax.swing.JPanel();
        cancelarAEmp = new javax.swing.JLabel();
        guardarAEmp = new javax.swing.JLabel();
        proveedor = new javax.swing.JLabel();
        proveedorCbx = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(228, 225, 225));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true), "Agregar nueva Cuenta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        noCuenta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        noCuenta.setText("NO. CUENTA:");

        banco.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        banco.setText("BANCO:");

        noCuentatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noCuentatxtActionPerformed(evt);
            }
        });

        opcionesAEmp.setBackground(new java.awt.Color(48, 45, 45));

        cancelarAEmp.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        cancelarAEmp.setForeground(new java.awt.Color(255, 255, 255));
        cancelarAEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        cancelarAEmp.setText("CANCELAR");
        cancelarAEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        cancelarAEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarAEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarAEmpMouseClicked(evt);
            }
        });

        guardarAEmp.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        guardarAEmp.setForeground(new java.awt.Color(255, 255, 255));
        guardarAEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        guardarAEmp.setText("GUARDAR ");
        guardarAEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        guardarAEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarAEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarAEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarAEmpMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout opcionesAEmpLayout = new javax.swing.GroupLayout(opcionesAEmp);
        opcionesAEmp.setLayout(opcionesAEmpLayout);
        opcionesAEmpLayout.setHorizontalGroup(
            opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesAEmpLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(guardarAEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(cancelarAEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        opcionesAEmpLayout.setVerticalGroup(
            opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesAEmpLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarAEmp)
                    .addComponent(guardarAEmp))
                .addGap(45, 45, 45))
        );

        proveedor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        proveedor.setText("PROVEEDOR:");

        proveedorCbx.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        proveedorCbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONA UN PROVEEDOR" }));
        proveedorCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorCbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcionesAEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(proveedor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noCuenta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(banco, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(noCuentatxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proveedorCbx, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bancotxt))
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedor)
                    .addComponent(proveedorCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noCuenta)
                    .addComponent(noCuentatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banco)
                    .addComponent(bancotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(opcionesAEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarAEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarAEmpMouseClicked
        try {
            if (proveedorCbx.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this, "Seleccione un proveedor\n, en caso de no tener uno, debe registrar un proveedor", "ERROR", JOptionPane.ERROR_MESSAGE);
                proveedorCbx.requestFocus();
            } else if (noCuentatxt.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ingrese el numero de cuenta", "ERROR", JOptionPane.ERROR_MESSAGE);
                noCuentatxt.requestFocus();
            } else if (bancotxt.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ingrese el nombre del banco", "ERROR", JOptionPane.ERROR_MESSAGE);
                bancotxt.requestFocus();
            } else {
                try {
                    new DAOCuentaProveedorImp().Insert(new CuentasProveedor(proveedorCbx.getSelectedItem().toString(),
                            noCuentatxt.getText(),
                            bancotxt.getText()));
                    limpiarVariables();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, " solo numeros", "Error de tipo de dato", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Capacidad solo numeros", "Error de tipo de dato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarAEmpMouseClicked

    private void cancelarAEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarAEmpMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        mostrarCuentasProveedor mostrarCuentaPro = new mostrarCuentasProveedor();
        mostrarCuentaPro.setSize(mainPrincipal.getworkSpace().getSize());
        mostrarCuentaPro.setVisible(true);
        mostrarCuentaPro.setMostrarCuentasProveedor(mainPrincipal);
        mostrarCuentaPro.MostrarDatosCuentasProv();
        mainPrincipal.getworkSpace().add(mostrarCuentaPro, BorderLayout.CENTER);
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();

    }//GEN-LAST:event_cancelarAEmpMouseClicked

    private void limpiarVariables() {
        proveedorCbx.setSelectedIndex(0);
        noCuentatxt.setText("");
        bancotxt.setText("");

    }

    private void guardarAEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarAEmpMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarAEmpMouseEntered

    private void noCuentatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noCuentatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noCuentatxtActionPerformed

    private void proveedorCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorCbxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banco;
    private javax.swing.JTextField bancotxt;
    private javax.swing.JLabel cancelarAEmp;
    private javax.swing.JLabel guardarAEmp;
    private javax.swing.JLabel noCuenta;
    private javax.swing.JTextField noCuentatxt;
    private javax.swing.JPanel opcionesAEmp;
    private javax.swing.JLabel proveedor;
    private javax.swing.JComboBox proveedorCbx;
    // End of variables declaration//GEN-END:variables

}
