/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Productos;

import Vistas.Empaques.*;
import DAOs.DAOEmpaquesImp;
import DAOs.DAOProductosImp;
import DAOs.Empaques;
import DAOs.Productos;
import java.awt.BorderLayout;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import MainPrincipal.Main;

/**
 *
 * @author 52351
 */
public class agregarProducto extends javax.swing.JPanel {

    /**
     * Creates new form agregarEmpaque
     */
    public agregarProducto() {
        initComponents();
        mostrarLaboratorios();
        mostrarCategorias();
        cajasDetexto();
        
    }

    private void mostrarLaboratorios() {
        LinkedList<Productos> productosLab = new DAOProductosImp().obternerIdLaboratorios();
        DefaultComboBoxModel model = (DefaultComboBoxModel) JCBoxLaboUPro.getModel();
        for (int i = 0; i < productosLab.size(); i++) {
            model.addElement(productosLab.get(i).getIdLab());
        }
        JCBoxLaboUPro.setModel(model);
    }
    
    private void mostrarCategorias() {
        LinkedList<Productos> productosCat = new DAOProductosImp().obternerIdCategorias();
        DefaultComboBoxModel model = (DefaultComboBoxModel) JCBoxCateUPro.getModel();
        for (int i = 0; i < productosCat.size(); i++) {
            model.addElement(productosCat.get(i).getIdCat());
        }
        JCBoxCateUPro.setModel(model);
    }
    private Main mainPrincipal;

    public void setMainPrincipal(Main main) {
        mainPrincipal = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesAEmp = new javax.swing.JPanel();
        cancelarAPro = new javax.swing.JLabel();
        guardarAPro = new javax.swing.JLabel();
        origenUEmp = new javax.swing.JLabel();
        origenUEmp7 = new javax.swing.JLabel();
        origenUEmp6 = new javax.swing.JLabel();
        origenUEmp3 = new javax.swing.JLabel();
        origenUEmp2 = new javax.swing.JLabel();
        JCBoxLaboUPro = new javax.swing.JComboBox<>();
        JCBoxCateUPro = new javax.swing.JComboBox<>();
        estatusUEmp = new javax.swing.JLabel();
        preordenTxt = new javax.swing.JTextField();
        origenUEmp1 = new javax.swing.JLabel();
        origenUEmp4 = new javax.swing.JLabel();
        nombreUEmp = new javax.swing.JLabel();
        origenUEmp8 = new javax.swing.JLabel();
        origenUEmp5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripTxt = new javax.swing.JTextArea();
        nombretxt = new javax.swing.JTextField();
        pCompTxt = new javax.swing.JTextField();
        pVentaTxt = new javax.swing.JTextField();
        iActivoTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        usoTxt = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        aplicTxt = new javax.swing.JTextArea();
        bToxicTxt = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(228, 225, 225));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true), "Agregar un nuevo empaque", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        opcionesAEmp.setBackground(new java.awt.Color(48, 45, 45));

        cancelarAPro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        cancelarAPro.setForeground(new java.awt.Color(255, 255, 255));
        cancelarAPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        cancelarAPro.setText("CANCELAR");
        cancelarAPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        cancelarAPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarAPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarAProMouseClicked(evt);
            }
        });

        guardarAPro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        guardarAPro.setForeground(new java.awt.Color(255, 255, 255));
        guardarAPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        guardarAPro.setText("GUARDAR ");
        guardarAPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        guardarAPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarAPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarAProMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarAProMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout opcionesAEmpLayout = new javax.swing.GroupLayout(opcionesAEmp);
        opcionesAEmp.setLayout(opcionesAEmpLayout);
        opcionesAEmpLayout.setHorizontalGroup(
            opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesAEmpLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(guardarAPro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarAPro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        opcionesAEmpLayout.setVerticalGroup(
            opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesAEmpLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarAPro)
                    .addComponent(cancelarAPro))
                .addContainerGap())
        );

        origenUEmp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp.setText("DESCRIPCIÓN:");

        origenUEmp7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp7.setText("USO:");

        origenUEmp6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp6.setText("APLICACIÓN:");

        origenUEmp3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp3.setText("PRECIO COMPRA:");

        origenUEmp2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp2.setText("PRECIO VENTA:");

        JCBoxLaboUPro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JCBoxLaboUPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE UNA OPCIÓN" }));

        JCBoxCateUPro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JCBoxCateUPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE UNA OPCIÓN" }));

        estatusUEmp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        estatusUEmp.setText("ID LABORATORIO:");

        origenUEmp1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp1.setText("PUNTO REORDEN:");

        origenUEmp4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp4.setText("BANDA TOXICOLÓGICA:");

        nombreUEmp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nombreUEmp.setText("NOMBRE:");

        origenUEmp8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp8.setText("ID CATEGORIA:");

        origenUEmp5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp5.setText("INGREDIENTE ACTIVO:");

        descripTxt.setColumns(20);
        descripTxt.setRows(5);
        jScrollPane1.setViewportView(descripTxt);

        nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxtActionPerformed(evt);
            }
        });

        iActivoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActivoTxtActionPerformed(evt);
            }
        });

        usoTxt.setColumns(20);
        usoTxt.setRows(5);
        jScrollPane2.setViewportView(usoTxt);

        aplicTxt.setColumns(20);
        aplicTxt.setRows(5);
        jScrollPane3.setViewportView(aplicTxt);

        bToxicTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bToxicTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE UNA OPCIÓN", "l a - Producto Sumamente Peligro (Muy tóxico)", "l b - Producto Muy Peligroso (Tóxico)", "ll - Producto Moderadamente Peligroso (Nocivo)", "lll - Producto Poco Peligroso (Cuidado)", "lV - Producto que no Ofrece Peligro (Cuidado)" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origenUEmp6)
                                    .addComponent(origenUEmp)
                                    .addComponent(nombreUEmp))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origenUEmp4)
                                    .addComponent(origenUEmp7)
                                    .addComponent(origenUEmp5)
                                    .addComponent(origenUEmp2)
                                    .addComponent(origenUEmp3)
                                    .addComponent(origenUEmp1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(preordenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pCompTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pVentaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iActivoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addComponent(estatusUEmp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JCBoxLaboUPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(bToxicTxt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(origenUEmp8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JCBoxCateUPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(opcionesAEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(origenUEmp)
                        .addGap(18, 18, 18)
                        .addComponent(origenUEmp1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(origenUEmp3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(origenUEmp2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(origenUEmp5)
                            .addComponent(iActivoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(origenUEmp4)
                            .addComponent(bToxicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(origenUEmp6)
                                .addGap(18, 18, 18)
                                .addComponent(origenUEmp7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreUEmp)
                            .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preordenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pCompTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pVentaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenUEmp8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBoxCateUPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estatusUEmp)
                    .addComponent(JCBoxLaboUPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionesAEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarAProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarAProMouseClicked
        if (preordenTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,"Ingrese un nombre válido","Error",JOptionPane.ERROR_MESSAGE);
            preordenTxt.requestFocus();
        }else if(descripTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese una descripción válido","Error",JOptionPane.ERROR_MESSAGE);
         descripTxt.requestFocus();
        } else if (preordenTxt.getText().equals("") || Integer.parseInt(preordenTxt.getText()) <= 0) {
            JOptionPane.showMessageDialog(this,"Ingrese un entero válido ","Error",JOptionPane.ERROR_MESSAGE);
            preordenTxt.requestFocus();
        } else if (pCompTxt.getText().equals("") || Float.parseFloat(pCompTxt.getText()) <= 0) {
            JOptionPane.showMessageDialog(this,"Ingrese un precio válido ","Error",JOptionPane.ERROR_MESSAGE);
            pCompTxt.requestFocus();
        } else if (pVentaTxt.getText().equals("") || Float.parseFloat(pVentaTxt.getText()) <= 0) {
            JOptionPane.showMessageDialog(this,"Ingrese un precio válido ","Error",JOptionPane.ERROR_MESSAGE);
            pVentaTxt.requestFocus();
        }else if(iActivoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese un ingrediente válido ","Error",JOptionPane.ERROR_MESSAGE);
         iActivoTxt.requestFocus();
        }else if(bToxicTxt.getSelectedIndex() <= 0){
            JOptionPane.showMessageDialog(this,"Ingrese una banda toxicológica válida ","Error",JOptionPane.ERROR_MESSAGE);
         bToxicTxt.requestFocus();
        }else if(aplicTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese una aplicación válida ","Error",JOptionPane.ERROR_MESSAGE);
         aplicTxt.requestFocus();
        }else if(usoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese un uso válido ","Error",JOptionPane.ERROR_MESSAGE);
         usoTxt.requestFocus();
        } else if (JCBoxLaboUPro.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,"Elija un laboratorio válido ","Error",JOptionPane.ERROR_MESSAGE);
            JCBoxLaboUPro.requestFocus();
        } else if (JCBoxCateUPro.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,"Elija una categoria válido ","Error",JOptionPane.ERROR_MESSAGE);
            JCBoxCateUPro.requestFocus();
        } else {
            
                new DAOProductosImp().Insert(new Productos(
                nombretxt.getText(),descripTxt.getText(), Integer.parseInt(preordenTxt.getText()),
                Float.parseFloat(pCompTxt.getText()),Float.parseFloat(pVentaTxt.getText()),
                iActivoTxt.getText(),bToxicTxt.getSelectedItem().toString(),aplicTxt.getText(),
                usoTxt.getText(),JCBoxLaboUPro.getSelectedItem().toString(),JCBoxCateUPro.getSelectedItem().toString()
                ));
                
                limpiarVariables();
            
        }

    }//GEN-LAST:event_guardarAProMouseClicked

    private void cancelarAProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarAProMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        mostrarProductos mostrarPro = new mostrarProductos();
        mostrarPro.setSize(mainPrincipal.getworkSpace().getSize());
        mostrarPro.setVisible(true);
        mostrarPro.setMostrarProductos(mainPrincipal);
        mostrarPro.MostrarDatosProductos();
        mainPrincipal.getworkSpace().add(mostrarPro, BorderLayout.CENTER);
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();

    }//GEN-LAST:event_cancelarAProMouseClicked

    private void limpiarVariables(){
        preordenTxt.setText("");
        descripTxt.setText("");
        preordenTxt.setText("");
        pCompTxt.setText("");
        pVentaTxt.setText("");
        iActivoTxt.setText("");
        bToxicTxt.setSelectedIndex(0);
        aplicTxt.setText("");
        usoTxt.setText("");
        JCBoxCateUPro.setSelectedIndex(0);
        JCBoxLaboUPro.setSelectedIndex(0);      
    }
    
    private void cajasDetexto(){
        descripTxt.setLineWrap(true);
        descripTxt.setWrapStyleWord(true);
        aplicTxt.setLineWrap(true);
        aplicTxt.setWrapStyleWord(true);
        usoTxt.setLineWrap(true);
        usoTxt.setWrapStyleWord(true);
    }
    
    private void guardarAProMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarAProMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarAProMouseEntered

    private void nombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretxtActionPerformed

    private void iActivoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActivoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iActivoTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCBoxCateUPro;
    private javax.swing.JComboBox<String> JCBoxLaboUPro;
    private javax.swing.JTextArea aplicTxt;
    private javax.swing.JComboBox<String> bToxicTxt;
    private javax.swing.JLabel cancelarAPro;
    private javax.swing.JTextArea descripTxt;
    private javax.swing.JLabel estatusUEmp;
    private javax.swing.JLabel guardarAPro;
    private javax.swing.JTextField iActivoTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nombreUEmp;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JPanel opcionesAEmp;
    private javax.swing.JLabel origenUEmp;
    private javax.swing.JLabel origenUEmp1;
    private javax.swing.JLabel origenUEmp2;
    private javax.swing.JLabel origenUEmp3;
    private javax.swing.JLabel origenUEmp4;
    private javax.swing.JLabel origenUEmp5;
    private javax.swing.JLabel origenUEmp6;
    private javax.swing.JLabel origenUEmp7;
    private javax.swing.JLabel origenUEmp8;
    private javax.swing.JTextField pCompTxt;
    private javax.swing.JTextField pVentaTxt;
    private javax.swing.JTextField preordenTxt;
    private javax.swing.JTextArea usoTxt;
    // End of variables declaration//GEN-END:variables

}
