package Vistas.Proveedores;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USERID
 */
public class agregarProveedor extends javax.swing.JFrame {

    /**
     * Creates new form agregarProveedor
     */
    public agregarProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        opcionesAEmp = new javax.swing.JPanel();
        cancelarAPro = new javax.swing.JLabel();
        guardarAPro = new javax.swing.JLabel();
        origenUEmp = new javax.swing.JLabel();
        origenUEmp3 = new javax.swing.JLabel();
        origenUEmp2 = new javax.swing.JLabel();
        JCBoxCateUPro = new javax.swing.JComboBox<String>();
        Emailtxt = new javax.swing.JTextField();
        origenUEmp1 = new javax.swing.JLabel();
        nombreUEmp = new javax.swing.JLabel();
        origenUEmp8 = new javax.swing.JLabel();
        origenUEmp5 = new javax.swing.JLabel();
        Telefonotxt = new javax.swing.JTextField();
        Direcciontxt = new javax.swing.JTextField();
        Coloniatxt = new javax.swing.JTextField();
        CodigoPostxt = new javax.swing.JTextField();
        nombretxt1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 225, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true), "Agregar un nuevo Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        opcionesAEmp.setBackground(new java.awt.Color(48, 45, 45));

        cancelarAPro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        cancelarAPro.setForeground(new java.awt.Color(255, 255, 255));
        cancelarAPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        cancelarAPro.setText("CANCELAR");
        cancelarAPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        cancelarAPro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelarAPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarAProMouseClicked(evt);
            }
        });

        guardarAPro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        guardarAPro.setForeground(new java.awt.Color(255, 255, 255));
        guardarAPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        guardarAPro.setText("GUARDAR ");
        guardarAPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        guardarAPro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        guardarAPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarAProMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarAProMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout opcionesAEmpLayout = new javax.swing.GroupLayout(opcionesAEmp);
        opcionesAEmp.setLayout(opcionesAEmpLayout);
        opcionesAEmpLayout.setHorizontalGroup(
            opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesAEmpLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(guardarAPro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addComponent(cancelarAPro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        opcionesAEmpLayout.setVerticalGroup(
            opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesAEmpLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarAPro)
                    .addComponent(cancelarAPro))
                .addContainerGap())
        );

        origenUEmp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp.setText("TELEFONO:");

        origenUEmp3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp3.setText("DIRECCIÓN:");

        origenUEmp2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp2.setText("COLONIA:");

        JCBoxCateUPro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JCBoxCateUPro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE UNA OPCIÓN" }));

        origenUEmp1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp1.setText("EMAIL:");

        nombreUEmp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nombreUEmp.setText("NOMBRE:");

        origenUEmp8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp8.setText("ID CIUDAD:");

        origenUEmp5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp5.setText("CODIGO POSTAL:");

        Telefonotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonotxtActionPerformed(evt);
            }
        });

        CodigoPostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoPostxtActionPerformed(evt);
            }
        });

        nombretxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcionesAEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(origenUEmp8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JCBoxCateUPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nombreUEmp)
                                            .addComponent(origenUEmp1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nombretxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(origenUEmp)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Telefonotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(origenUEmp3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Direcciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(origenUEmp2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Coloniatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(origenUEmp5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CodigoPostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUEmp)
                    .addComponent(nombretxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origenUEmp)
                    .addComponent(Telefonotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenUEmp1)
                    .addComponent(Emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origenUEmp3)
                    .addComponent(Direcciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenUEmp2)
                    .addComponent(Coloniatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origenUEmp5)
                    .addComponent(CodigoPostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenUEmp8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBoxCateUPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionesAEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarAProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarAProMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        mostrarProductos mostrarPro = new mostrarProductos();
        mostrarPro.setSize(mainPrincipal.getworkSpace().getSize());
        mostrarPro.setVisible(true);
        mostrarPro.setMostrarProductos(mainPrincipal);
        mostrarPro.MostrarDatosProductos();
        mainPrincipal.getworkSpace().add(mostrarPro, BorderLayout.CENTER);
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();
    }//GEN-LAST:event_cancelarAProMouseClicked

    private void guardarAProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarAProMouseClicked
        if (Emailtxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,"Ingrese un nombre válido","Error",JOptionPane.ERROR_MESSAGE);
            Emailtxt.requestFocus();
        }else if(descripTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese una descripción válido","Error",JOptionPane.ERROR_MESSAGE);
            descripTxt.requestFocus();
        } else if (Emailtxt.getText().equals("") || Integer.parseInt(Emailtxt.getText()) <= 0) {
            JOptionPane.showMessageDialog(this,"Ingrese un entero válido ","Error",JOptionPane.ERROR_MESSAGE);
            Emailtxt.requestFocus();
        } else if (Direcciontxt.getText().equals("") || Float.parseFloat(Direcciontxt.getText()) <= 0) {
            JOptionPane.showMessageDialog(this,"Ingrese un precio válido ","Error",JOptionPane.ERROR_MESSAGE);
            Direcciontxt.requestFocus();
        } else if (Coloniatxt.getText().equals("") || Float.parseFloat(Coloniatxt.getText()) <= 0) {
            JOptionPane.showMessageDialog(this,"Ingrese un precio válido ","Error",JOptionPane.ERROR_MESSAGE);
            Coloniatxt.requestFocus();
        }else if(CodigoPostxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese un ingrediente válido ","Error",JOptionPane.ERROR_MESSAGE);
            CodigoPostxt.requestFocus();
        }else if(bToxicTxt.getSelectedIndex() <= 0){
            JOptionPane.showMessageDialog(this,"Ingrese una banda toxicológica válida ","Error",JOptionPane.ERROR_MESSAGE);
            bToxicTxt.requestFocus();
        }else if(aplicTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese una aplicación válida ","Error",JOptionPane.ERROR_MESSAGE);
            aplicTxt.requestFocus();
        }else if(usoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese un uso válido ","Error",JOptionPane.ERROR_MESSAGE);
            usoTxt.requestFocus();
        } else if (JCBoxLaboUPro.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,"Elija un laboratorio válido ","Error",JOptionPane.ERROR_MESSAGE);
            JCBoxLaboUPro.requestFocus();
        } else if (JCBoxCateUPro.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,"Elija una categoria válido ","Error",JOptionPane.ERROR_MESSAGE);
            JCBoxCateUPro.requestFocus();
        } else {

            new DAOProductosImp().Insert(new Productos(
                Telefonotxt.getText(),descripTxt.getText(), Integer.parseInt(Emailtxt.getText()),
                Float.parseFloat(Direcciontxt.getText()),Float.parseFloat(Coloniatxt.getText()),
                CodigoPostxt.getText(),bToxicTxt.getSelectedItem().toString(),aplicTxt.getText(),
                usoTxt.getText(),JCBoxLaboUPro.getSelectedItem().toString(),JCBoxCateUPro.getSelectedItem().toString()
            ));

            limpiarVariables();

        }
    }//GEN-LAST:event_guardarAProMouseClicked

    private void guardarAProMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarAProMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarAProMouseEntered

    private void TelefonotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonotxtActionPerformed

    private void CodigoPostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoPostxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoPostxtActionPerformed

    private void nombretxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretxt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoPostxt;
    private javax.swing.JTextField Coloniatxt;
    private javax.swing.JTextField Direcciontxt;
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JComboBox<String> JCBoxCateUPro;
    private javax.swing.JTextField Telefonotxt;
    private javax.swing.JLabel cancelarAPro;
    private javax.swing.JLabel guardarAPro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreUEmp;
    private javax.swing.JTextField nombretxt1;
    private javax.swing.JPanel opcionesAEmp;
    private javax.swing.JLabel origenUEmp;
    private javax.swing.JLabel origenUEmp1;
    private javax.swing.JLabel origenUEmp2;
    private javax.swing.JLabel origenUEmp3;
    private javax.swing.JLabel origenUEmp5;
    private javax.swing.JLabel origenUEmp8;
    // End of variables declaration//GEN-END:variables
}
