/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Proveedores;

/**
 *
 * @author USERID
 */
public class modificarProveedor extends javax.swing.JFrame {

    /**
     * Creates new form modificarProveedor
     */
    public modificarProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        opcionesAEmp = new javax.swing.JPanel();
        cancelarAPro = new javax.swing.JLabel();
        modificarUPro = new javax.swing.JLabel();
        origenUEmp = new javax.swing.JLabel();
        origenUEmp3 = new javax.swing.JLabel();
        origenUEmp2 = new javax.swing.JLabel();
        idCiudad = new javax.swing.JComboBox<String>();
        Emailtxt = new javax.swing.JTextField();
        origenUEmp1 = new javax.swing.JLabel();
        nombreUEmp = new javax.swing.JLabel();
        origenUEmp8 = new javax.swing.JLabel();
        origenUEmp5 = new javax.swing.JLabel();
        Telefonotxt = new javax.swing.JTextField();
        Direcciontxt = new javax.swing.JTextField();
        Coloniatxt = new javax.swing.JTextField();
        CodigoPostxt = new javax.swing.JTextField();
        nombretxt1 = new javax.swing.JTextField();
        origenUEmp6 = new javax.swing.JLabel();
        estus = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 225, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true), "Modificar un Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        opcionesAEmp.setBackground(new java.awt.Color(48, 45, 45));

        cancelarAPro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        cancelarAPro.setForeground(new java.awt.Color(255, 255, 255));
        cancelarAPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        cancelarAPro.setText("CANCELAR");
        cancelarAPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        cancelarAPro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelarAPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarAProMouseClicked(evt);
            }
        });

        modificarUPro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        modificarUPro.setForeground(new java.awt.Color(255, 255, 255));
        modificarUPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        modificarUPro.setText("MODIFICAR");
        modificarUPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        modificarUPro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificarUPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarUProMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesAEmpLayout = new javax.swing.GroupLayout(opcionesAEmp);
        opcionesAEmp.setLayout(opcionesAEmpLayout);
        opcionesAEmpLayout.setHorizontalGroup(
            opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesAEmpLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(modificarUPro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarAPro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        opcionesAEmpLayout.setVerticalGroup(
            opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesAEmpLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(opcionesAEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarAPro)
                    .addComponent(modificarUPro))
                .addContainerGap())
        );

        origenUEmp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp.setText("TELEFONO:");

        origenUEmp3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp3.setText("DIRECCIÓN:");

        origenUEmp2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp2.setText("COLONIA:");

        idCiudad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        idCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE UNA OPCIÓN" }));

        origenUEmp1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp1.setText("EMAIL:");

        nombreUEmp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nombreUEmp.setText("NOMBRE:");

        origenUEmp8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp8.setText("ID CIUDAD:");

        origenUEmp5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp5.setText("ESTATUS:");

        Telefonotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonotxtActionPerformed(evt);
            }
        });

        CodigoPostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoPostxtActionPerformed(evt);
            }
        });

        nombretxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxt1ActionPerformed(evt);
            }
        });

        origenUEmp6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        origenUEmp6.setText("CODIGO POSTAL:");

        estus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE UNA OPCIÓN", "ACTIVO", "INACTIVO" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcionesAEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreUEmp)
                                    .addComponent(origenUEmp1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombretxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(origenUEmp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Telefonotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(origenUEmp3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Direcciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(origenUEmp2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Coloniatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(origenUEmp6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CodigoPostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(origenUEmp8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(origenUEmp5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estus, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUEmp)
                    .addComponent(nombretxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origenUEmp)
                    .addComponent(Telefonotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenUEmp1)
                    .addComponent(Emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origenUEmp3)
                    .addComponent(Direcciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenUEmp2)
                    .addComponent(Coloniatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoPostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origenUEmp6))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenUEmp8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origenUEmp5)
                    .addComponent(estus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(opcionesAEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarAProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarAProMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        mostrarProductos mostrarPro = new mostrarProductos();
        mostrarPro.setSize(mainPrincipal.getworkSpace().getSize());
        mostrarPro.setVisible(true);
        mostrarPro.setMostrarProductos(mainPrincipal);
        mostrarPro.MostrarDatosProductos();
        mainPrincipal.getworkSpace().add(mostrarPro, BorderLayout.CENTER);
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();
    }//GEN-LAST:event_cancelarAProMouseClicked

    private void TelefonotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonotxtActionPerformed

    private void CodigoPostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoPostxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoPostxtActionPerformed

    private void nombretxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretxt1ActionPerformed

    private void modificarUProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarUProMouseClicked
        if (nombretxtPro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre válido", "Error", JOptionPane.ERROR_MESSAGE);
            nombretxtPro.requestFocus();
        }
        try {
            if (pReordenTxt.getText().equals("")||Float.parseFloat(pCompreTxt.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Ingrese un numero valido", "Error", JOptionPane.ERROR_MESSAGE);
                pReordenTxt.requestFocus();
            } else if (pCompreTxt.getText().equals("") || Float.parseFloat(pCompreTxt.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Ingrese un precio válido ", "Error", JOptionPane.ERROR_MESSAGE);
                pCompreTxt.requestFocus();
            } else if (Coloniatxt.getText().equals("") || Float.parseFloat(Coloniatxt.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Ingrese un precio válido ", "Error", JOptionPane.ERROR_MESSAGE);
                Coloniatxt.requestFocus();
            } else if (CodigoPostxt.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ingrese una ingrediente activo ", "Error", JOptionPane.ERROR_MESSAGE);
                CodigoPostxt.requestFocus();
            } else if (bToxic.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this, "Ingrese una banda toxicológica válida ", "Error", JOptionPane.ERROR_MESSAGE);
                bToxic.requestFocus();
            } else if (aplicaTxt.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ingrese una aplicación válida ", "Error", JOptionPane.ERROR_MESSAGE);
                aplicaTxt.requestFocus();
            } else if (usoTxt.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ingrese un uso válido ", "Error", JOptionPane.ERROR_MESSAGE);
                usoTxt.requestFocus();
            } else if (laboratorio.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this, "Elija un laboratorio válido ", "Error", JOptionPane.ERROR_MESSAGE);
                laboratorio.requestFocus();
            } else if (categ.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this, "Elija una categoria válido ", "Error", JOptionPane.ERROR_MESSAGE);
                categ.requestFocus();
            } else {
                DAOProductosImp guardarPro = new DAOProductosImp();
                //Datos obtenidos de los campos
                int id = Integer.parseInt(this.idtxtUPro.getText());
                String nombre = this.nombretxtPro.getText();
                String descripcion = this.descripTxt.getText();
                int puntoreorden = Integer.parseInt(this.pReordenTxt.getText());
                float precioventa = Float.parseFloat(this.Coloniatxt.getText());
                float preciocompra = Float.parseFloat(this.pCompreTxt.getText());
                String ingrediente = this.CodigoPostxt.getText();
                String banda = this.bToxic.getSelectedItem().toString();
                String aplicacion = this.aplicaTxt.getText();
                String uso = this.usoTxt.getText();
                char estatus = String.valueOf(this.estus.getSelectedItem()).charAt(0);
                String laboratorio = this.laboratorio.getSelectedItem().toString();
                String categoria = this.categ.getSelectedItem().toString();
                //Guardar los datos de laboratorio
                guardarPro.upadate(new Productos(id, nombre, descripcion, puntoreorden, preciocompra, precioventa,
                    ingrediente, banda, aplicacion, uso, estatus, laboratorio, categoria));
            limpiarVariables();
        }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_modificarUProMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificarProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoPostxt;
    private javax.swing.JTextField Coloniatxt;
    private javax.swing.JTextField Direcciontxt;
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JTextField Telefonotxt;
    private javax.swing.JLabel cancelarAPro;
    private javax.swing.JComboBox<String> estus;
    private javax.swing.JComboBox<String> idCiudad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modificarUPro;
    private javax.swing.JLabel nombreUEmp;
    private javax.swing.JTextField nombretxt1;
    private javax.swing.JPanel opcionesAEmp;
    private javax.swing.JLabel origenUEmp;
    private javax.swing.JLabel origenUEmp1;
    private javax.swing.JLabel origenUEmp2;
    private javax.swing.JLabel origenUEmp3;
    private javax.swing.JLabel origenUEmp5;
    private javax.swing.JLabel origenUEmp6;
    private javax.swing.JLabel origenUEmp8;
    // End of variables declaration//GEN-END:variables
}
