/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Proveedores;

import DAOs.DAOProveedoresImp;
import DAOs.Proveedores;
import MainPrincipal.Main;
import java.awt.BorderLayout;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import DAOs.DAOProveedoresImp;
import DAOs.Proveedores;
import MainPrincipal.Main;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class mostrarProveedor extends javax.swing.JPanel {
private Main mainPrincipal;
    /**
     * Creates new form mostrarProveedor
     */
    public mostrarProveedor() {
        initComponents();
        ContRegistros = new DAOProveedoresImp().contRegistros();
        ContRegistros = Math.ceil((ContRegistros / 10));
        leyenda.setVisible(false);
    }

    private double ContRegistros;
    private int CambioPagina = 1;

    public void setMostrarProveedor(Main worksapce) {
        mainPrincipal = worksapce;
    }

    public void MostrarDatosProveedor() {
        LinkedList<Proveedores> prov = new DAOProveedoresImp().show(CambioPagina);
        if (ContRegistros <= 0) {
            next.setVisible(false);
            preview.setVisible(false);
            return;
        } else {
            next.setVisible(true);
            preview.setVisible(true);
            this.segmentacion.setText("Página" + CambioPagina + " de " + (int) ContRegistros + " Paginas en total");
            Object listaDatos[][] = new Object[prov.size()][9];
            for (int i = 0; i < prov.size(); i++) {
                listaDatos[i][0] = prov.get(i).getIdProvedor();
                listaDatos[i][1] = prov.get(i).getNombre();
                listaDatos[i][2] = prov.get(i).getEmail();
                listaDatos[i][3] = prov.get(i).getTelefono();
                listaDatos[i][4] = prov.get(i).getColonia();
                listaDatos[i][5] = prov.get(i).getDireccion();
                listaDatos[i][6] = prov.get(i).getCodPostall();
                listaDatos[i][7] = prov.get(i).getStatus();
                listaDatos[i][8] = prov.get(i).getIdCiudad();
            }
            DefaultTableModel modelTable = new DefaultTableModel(
                    listaDatos,
                    new Object[]{"IDPROVEEDOR", "NOMBRE", "EMAIL", "TELEFONO",
                        "COLONIA", "DIRECCIÓN", "CODIGO POSTAL", "ESTATUS", "IDCIUDAD"}) {
                        public boolean isCellEditable(int row, int colum) {
                            return false;
                        }
                    };
            this.TablaProveedor.setModel(modelTable);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMostrarPro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProveedor = new javax.swing.JTable();
        buscartxtMPro = new javax.swing.JTextField();
        BuscarProveedor = new javax.swing.JLabel();
        opcionesMostrarEmp = new javax.swing.JPanel();
        NuevoProveedor = new javax.swing.JLabel();
        CancelarProveedor = new javax.swing.JLabel();
        opcionesMostrarLab3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        segmentacion = new javax.swing.JLabel();
        preview = new javax.swing.JButton();
        next = new javax.swing.JButton();
        leyenda = new javax.swing.JLabel();

        mainMostrarPro.setBackground(new java.awt.Color(233, 231, 231));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        TablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "EMAIL", "TELEFONO", "DIIRECCIÓN", "COLONIA", "CODIGO POSTAL", "ESTATUS", "IDCIUDAD"
            }
        ));
        TablaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProveedor);

        BuscarProveedor.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        BuscarProveedor.setForeground(new java.awt.Color(102, 102, 102));
        BuscarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/most.png"))); // NOI18N
        BuscarProveedor.setText("BUSCAR PROVEEDOR");
        BuscarProveedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        BuscarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BuscarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarProveedorMouseClicked(evt);
            }
        });

        opcionesMostrarEmp.setBackground(new java.awt.Color(48, 45, 45));

        NuevoProveedor.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        NuevoProveedor.setForeground(new java.awt.Color(255, 255, 255));
        NuevoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        NuevoProveedor.setText("NUEVO PROVEEDOR");
        NuevoProveedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        NuevoProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NuevoProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuevoProveedorMouseClicked(evt);
            }
        });

        CancelarProveedor.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        CancelarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        CancelarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        CancelarProveedor.setText("CANCELAR");
        CancelarProveedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        CancelarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CancelarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarProveedorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesMostrarEmpLayout = new javax.swing.GroupLayout(opcionesMostrarEmp);
        opcionesMostrarEmp.setLayout(opcionesMostrarEmpLayout);
        opcionesMostrarEmpLayout.setHorizontalGroup(
            opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesMostrarEmpLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(NuevoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        opcionesMostrarEmpLayout.setVerticalGroup(
            opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarEmpLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NuevoProveedor)
                    .addComponent(CancelarProveedor))
                .addGap(21, 21, 21))
        );

        opcionesMostrarLab3.setBackground(java.awt.Color.lightGray);

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Cambio pagina \"cada página contiene 10 registros.");

        segmentacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        preview.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N
        preview.setText("Anterior");
        preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewMouseClicked(evt);
            }
        });

        next.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha.png"))); // NOI18N
        next.setText("Siguiente");
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesMostrarLab3Layout = new javax.swing.GroupLayout(opcionesMostrarLab3);
        opcionesMostrarLab3.setLayout(opcionesMostrarLab3Layout);
        opcionesMostrarLab3Layout.setHorizontalGroup(
            opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                .addGroup(opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(preview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(next))
                    .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opcionesMostrarLab3Layout.setVerticalGroup(
            opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preview)
                    .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        leyenda.setBackground(new java.awt.Color(255, 0, 51));
        leyenda.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(255, 51, 51));
        leyenda.setText("No se encuentran mas registros en paginas.");

        javax.swing.GroupLayout mainMostrarProLayout = new javax.swing.GroupLayout(mainMostrarPro);
        mainMostrarPro.setLayout(mainMostrarProLayout);
        mainMostrarProLayout.setHorizontalGroup(
            mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opcionesMostrarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMostrarProLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(leyenda)
                .addGap(222, 222, 222))
            .addGroup(mainMostrarProLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMostrarProLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMostrarProLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMostrarProLayout.createSequentialGroup()
                                .addComponent(buscartxtMPro, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMostrarProLayout.createSequentialGroup()
                                .addComponent(opcionesMostrarLab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))))))
        );
        mainMostrarProLayout.setVerticalGroup(
            mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMostrarProLayout.createSequentialGroup()
                .addGroup(mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarProveedor)
                    .addComponent(buscartxtMPro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcionesMostrarLab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(leyenda)
                .addGap(7, 7, 7)
                .addComponent(opcionesMostrarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMostrarPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMostrarPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TablaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProveedorMouseClicked
        int row;
        row = TablaProveedor.getSelectedRow();
        //Verificamos que el evento este en el rango de la tabla.
        if (row > -1 && row <= TablaProveedor.getSelectedRow()) {
            //creamos la ventana modificar
            modificarProveedor modificarProve = new modificarProveedor();
            this.mainPrincipal.getworkSpace().removeAll();
            modificarProve.setSize(mainPrincipal.getworkSpace().getSize());
            modificarProve.setVisible(true);
            modificarProve.setMainPrincipal(mainPrincipal);
            //Datos de la tabla, selecionar un row
            int IdProveedor = Integer.parseInt(String.valueOf(this.TablaProveedor.getValueAt(row, 0)));
            String Nombre = String.valueOf(this.TablaProveedor.getValueAt(row, 1));
            String Telefono = String.valueOf(this.TablaProveedor.getValueAt(row, 2));
            String Email = String.valueOf(this.TablaProveedor.getValueAt(row, 3)).toString();
            String Colonia = String.valueOf(this.TablaProveedor.getValueAt(row, 4));
            String Direccion = String.valueOf(this.TablaProveedor.getValueAt(row, 5));
            String CodigoPostal = String.valueOf(this.TablaProveedor.getValueAt(row, 6));
            char estatus = String.valueOf(this.TablaProveedor.getValueAt(row, 7)).charAt(0);
            String Ciudad = String.valueOf(this.TablaProveedor.getValueAt(row, 8));

            //Ingresan los datos de la tabla a la interfaz Modificar Laboratorio
            modificarProve.ObtenerProveedorModificar(new Proveedores(IdProveedor, Nombre, Email, Telefono,
                                                        Direccion, Colonia, CodigoPostal, Ciudad, estatus));
            
            this.mainPrincipal.getworkSpace().add(modificarProve, BorderLayout.CENTER);
            this.mainPrincipal.getworkSpace().revalidate();
            this.mainPrincipal.getworkSpace().repaint();
        }
    }//GEN-LAST:event_TablaProveedorMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void BuscarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarProveedorMouseClicked
        if (BuscarProveedor.getText() == "" || BuscarProveedor.getText() == null) {
            JOptionPane.showMessageDialog(null, "Debes escribir algo para filtrar...",
                "Mensaje", JOptionPane.WARNING_MESSAGE);
        } else {
            LinkedList<Proveedores> cat = new DAOProveedoresImp().consultaInd(BuscarProveedor.getText());
            Object listaDatos[][] = new Object[cat.size()][9];
            for (int i = 0; i < cat.size(); i++) {
                listaDatos[i][0] = cat.get(i).getIdProvedor();
                listaDatos[i][1] = cat.get(i).getNombre();
                listaDatos[i][2] = cat.get(i).getEmail();
                listaDatos[i][3] = cat.get(i).getTelefono();
                listaDatos[i][4] = cat.get(i).getColonia();
                listaDatos[i][5] = cat.get(i).getDireccion();
                listaDatos[i][6] = cat.get(i).getCodPostall();
                listaDatos[i][7] = cat.get(i).getStatus();
                listaDatos[i][8] = cat.get(i).getIdCiudad();

            }

            DefaultTableModel modelTable = new DefaultTableModel(
                listaDatos,
                new Object[]{"IDPROVEEDOR", "NOMBRE", "EMAIL",
                    "TELEFONO", "COLONIA", "DIRECCION",
                    "CODIGO POSTAL", "ESTATUS",
                    "CIUDAD"}) {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            this.TablaProveedor.setModel(modelTable);
        }
    }//GEN-LAST:event_BuscarProveedorMouseClicked

    private void NuevoProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoProveedorMouseClicked
        if (new DAOProveedoresImp().obtenerIdCiudad()!= null) {
            mainPrincipal.getworkSpace().removeAll();
            agregarProveedor nuevoProveedor = new agregarProveedor();
            nuevoProveedor.setSize(mainPrincipal.getworkSpace().getSize());
            nuevoProveedor.setVisible(true);
            nuevoProveedor.setMainPrincipal(mainPrincipal);
            mainPrincipal.getworkSpace().add(nuevoProveedor, BorderLayout.CENTER);
            mainPrincipal.getworkSpace().revalidate();
            mainPrincipal.getworkSpace().repaint();

        } else {
            JOptionPane.showMessageDialog(this, "Ciudades no disponibles, registre por lo menos una "
                + "ciudad en el sistema", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_NuevoProveedorMouseClicked

    private void CancelarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarProveedorMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();
    }//GEN-LAST:event_CancelarProveedorMouseClicked

    private void previewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewMouseClicked
        if (CambioPagina == 1) {
            preview.setVisible(false);
            next.setVisible(true);
            leyenda.setVisible(true);
            MostrarDatosProveedor();
        } else {
            next.setVisible(true);
            CambioPagina--;
            MostrarDatosProveedor();
            leyenda.setVisible(false);

        }
    }//GEN-LAST:event_previewMouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        if (CambioPagina >= ContRegistros) {
            next.setVisible(false);
            preview.setVisible(true);
            leyenda.setVisible(true);
            MostrarDatosProveedor();
        } else {
            CambioPagina++;
            preview.setVisible(true);
            MostrarDatosProveedor();
            leyenda.setVisible(false);
        }
    }//GEN-LAST:event_nextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscarProveedor;
    private javax.swing.JLabel CancelarProveedor;
    private javax.swing.JLabel NuevoProveedor;
    private javax.swing.JTable TablaProveedor;
    private javax.swing.JTextField buscartxtMPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leyenda;
    private javax.swing.JPanel mainMostrarPro;
    private javax.swing.JButton next;
    private javax.swing.JPanel opcionesMostrarEmp;
    private javax.swing.JPanel opcionesMostrarLab3;
    private javax.swing.JButton preview;
    private javax.swing.JLabel segmentacion;
    // End of variables declaration//GEN-END:variables
}
