/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.ImagenesProducto;

import DAOs.DAOImagenesProducto;
import DAOs.DAOImagenesProductoImp;
import DAOs.DAOPedidoDetalleImp;
import DAOs.DAOProductosImp;
import DAOs.ImagenesProducto;
import DAOs.PedidoDetalle;
import MainPrincipal.Main;
import java.awt.BorderLayout;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 52351
 */
public class mostrarImagenesproducto extends javax.swing.JPanel {

    /**
     * Creates new form mostrarEmpaques
     */
    public mostrarImagenesproducto() {
        initComponents();
        ContRegistro = new DAOProductosImp().contRegistros();
        ContRegistro = Math.ceil((ContRegistro / 10));
        leyenda.setVisible(false);
    }

    private double ContRegistro;
    private int cambioPagina = 1;

    public void activeEventListenerMostrarEmp() {
        MostrarDatosPedidoDetalle();
    }

    public void setMostrarPedidoDetalle(Main worksapce) {
        mainPrincipal = worksapce;
    }

    public void MostrarDatosPedidoDetalle() {
        LinkedList<ImagenesProducto> emp = new DAOImagenesProductoImp().show(cambioPagina);
        if (ContRegistro <= 0) {
            next.setVisible(false);
            preview.setVisible(false);
            return;
        } else {
            next.setVisible(true);
            preview.setVisible(true);
            this.segmentacion.setText("Página " + cambioPagina + " de " + (int) ContRegistro + " Páginas en total");
            Object listaDatos[][] = new Object[emp.size()][10];
            for (int i = 0; i < emp.size(); i++) {
                listaDatos[i][0] = emp.get(i).getIdImagen();
                listaDatos[i][1] = emp.get(i).getNombreImagen();
                listaDatos[i][2] = emp.get(i).getImagen();
                listaDatos[i][3] = emp.get(i).getPrincipal();
                listaDatos[i][4] = emp.get(i).getEstatus();
                listaDatos[i][5] = emp.get(i).getIdProducto();
            }

            DefaultTableModel modelTable = new DefaultTableModel(
                    listaDatos,
                    new Object[]{"ID", "NOMBIMAGEN", "IMAGEN",
                        "PRINCIPAL", "ESTATUS", "IDPRODUCTO"}) {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            this.jTableMImgPro.setModel(modelTable);
            this.jTableMImgPro.getColumnModel().getColumn(0).setMinWidth(10);
            this.jTableMImgPro.getColumnModel().getColumn(0).setMaxWidth(50);

            this.jTableMImgPro.getColumnModel().getColumn(1).setMinWidth(50);
            this.jTableMImgPro.getColumnModel().getColumn(1).setMaxWidth(350);

            this.jTableMImgPro.getColumnModel().getColumn(2).setMinWidth(50);
            this.jTableMImgPro.getColumnModel().getColumn(2).setMaxWidth(350);

            this.jTableMImgPro.getColumnModel().getColumn(3).setMinWidth(10);
            this.jTableMImgPro.getColumnModel().getColumn(3).setMaxWidth(200);

            this.jTableMImgPro.getColumnModel().getColumn(4).setMinWidth(10);
            this.jTableMImgPro.getColumnModel().getColumn(4).setMaxWidth(200);

            this.jTableMImgPro.getColumnModel().getColumn(5).setMinWidth(10);
            this.jTableMImgPro.getColumnModel().getColumn(5).setMaxWidth(200);


        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMostrarPro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMImgPro = new javax.swing.JTable();
        buscartxtMImgPro = new javax.swing.JTextField();
        buscarMImgPro = new javax.swing.JLabel();
        opcionesMostrarEmp = new javax.swing.JPanel();
        nuevoMImgPro = new javax.swing.JLabel();
        cancelarMImgPro = new javax.swing.JLabel();
        opcionesMostrarLab3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        segmentacion = new javax.swing.JLabel();
        preview = new javax.swing.JButton();
        next = new javax.swing.JButton();
        leyenda = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 231, 231));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true), "Mostrar productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        mainMostrarPro.setBackground(new java.awt.Color(233, 231, 231));

        jTableMImgPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBIMAGEN", "IMAGEN", "PRINCIPAL", "ESTATUS", "IDPRODUCTO"
            }
        ));
        jTableMImgPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMImgProMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMImgPro);

        buscarMImgPro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        buscarMImgPro.setForeground(new java.awt.Color(102, 102, 102));
        buscarMImgPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/most.png"))); // NOI18N
        buscarMImgPro.setText("BUSCAR PEDIDO");
        buscarMImgPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        buscarMImgPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarMImgPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMImgProMouseClicked(evt);
            }
        });

        opcionesMostrarEmp.setBackground(new java.awt.Color(48, 45, 45));

        nuevoMImgPro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        nuevoMImgPro.setForeground(new java.awt.Color(255, 255, 255));
        nuevoMImgPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        nuevoMImgPro.setText("NUEVO IMAGEN PRODUCTO");
        nuevoMImgPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        nuevoMImgPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevoMImgPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoMImgProMouseClicked(evt);
            }
        });

        cancelarMImgPro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        cancelarMImgPro.setForeground(new java.awt.Color(255, 255, 255));
        cancelarMImgPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        cancelarMImgPro.setText("CANCELAR");
        cancelarMImgPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        cancelarMImgPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarMImgPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMImgProMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesMostrarEmpLayout = new javax.swing.GroupLayout(opcionesMostrarEmp);
        opcionesMostrarEmp.setLayout(opcionesMostrarEmpLayout);
        opcionesMostrarEmpLayout.setHorizontalGroup(
            opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesMostrarEmpLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(nuevoMImgPro, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarMImgPro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        opcionesMostrarEmpLayout.setVerticalGroup(
            opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarEmpLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoMImgPro)
                    .addComponent(cancelarMImgPro))
                .addGap(21, 21, 21))
        );

        opcionesMostrarLab3.setBackground(java.awt.Color.lightGray);

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Cambio pagina \"cada página contiene 10 registros.");

        segmentacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        preview.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N
        preview.setText("Anterior");
        preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewMouseClicked(evt);
            }
        });

        next.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha.png"))); // NOI18N
        next.setText("Siguiente");
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesMostrarLab3Layout = new javax.swing.GroupLayout(opcionesMostrarLab3);
        opcionesMostrarLab3.setLayout(opcionesMostrarLab3Layout);
        opcionesMostrarLab3Layout.setHorizontalGroup(
            opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                .addGroup(opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(preview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(next))
                    .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opcionesMostrarLab3Layout.setVerticalGroup(
            opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preview)
                    .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        leyenda.setBackground(new java.awt.Color(255, 0, 51));
        leyenda.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(255, 51, 51));
        leyenda.setText("No se encuentran mas registros en paginas.");

        javax.swing.GroupLayout mainMostrarProLayout = new javax.swing.GroupLayout(mainMostrarPro);
        mainMostrarPro.setLayout(mainMostrarProLayout);
        mainMostrarProLayout.setHorizontalGroup(
            mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMostrarProLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMostrarProLayout.createSequentialGroup()
                        .addGap(0, 232, Short.MAX_VALUE)
                        .addComponent(buscartxtMImgPro, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarMImgPro, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(opcionesMostrarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(mainMostrarProLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(leyenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMostrarProLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opcionesMostrarLab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        mainMostrarProLayout.setVerticalGroup(
            mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMostrarProLayout.createSequentialGroup()
                .addGroup(mainMostrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarMImgPro)
                    .addComponent(buscartxtMImgPro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcionesMostrarLab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(leyenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(opcionesMostrarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMostrarPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMostrarPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Mostrar pedidoDetalle");
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoMImgProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMImgProMouseClicked
        if (new DAOImagenesProductoImp().obternerIdProducto()!= null ) {
            mainPrincipal.getworkSpace().removeAll();
            agregarImagenesProducto nuevoEmp = new agregarImagenesProducto();
            nuevoEmp.setSize(mainPrincipal.getworkSpace().getSize());
            nuevoEmp.setVisible(true);
            nuevoEmp.setMainPrincipal(mainPrincipal);
            mainPrincipal.getworkSpace().add(nuevoEmp, BorderLayout.CENTER);
            mainPrincipal.getworkSpace().revalidate();
            mainPrincipal.getworkSpace().repaint();

        } else {
            JOptionPane.showMessageDialog(this, "Productos no disponibles, registre por lo menos una "
                    + "Productos en el sistema", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_nuevoMImgProMouseClicked

    private void cancelarMImgProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMImgProMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();
    }//GEN-LAST:event_cancelarMImgProMouseClicked

    private void jTableMImgProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMImgProMouseClicked
        int row;
        row = jTableMImgPro.getSelectedRow();
        //Verificamos que el evento este en el rango de la tabla.
        if (row > -1 && row <= jTableMImgPro.getSelectedRow()) {
            //creamos la ventana modificar
            modificarImagenesProducto modificarEmpaque = new modificarImagenesProducto();
            this.mainPrincipal.getworkSpace().removeAll();
            modificarEmpaque.setSize(mainPrincipal.getworkSpace().getSize());
            modificarEmpaque.setVisible(true);
            modificarEmpaque.setMainPrincipal(mainPrincipal);
            //Datos de la tabla, selecionar un row

            int id = Integer.parseInt(String.valueOf(this.jTableMImgPro.getValueAt(row, 0)));
            String nombImg = String.valueOf(this.jTableMImgPro.getValueAt(row, 1));
            byte[] imagen = (String.valueOf(this.jTableMImgPro.getValueAt(row, 2))).getBytes();
            char principal = String.valueOf(this.jTableMImgPro.getValueAt(row, 3)).charAt(0);
            char estatus = String.valueOf(this.jTableMImgPro.getValueAt(row, 4)).charAt(0);
            String producto = (String.valueOf(this.jTableMImgPro.getValueAt(row, 5)));
            //Ingresan los datos de la tabla a la interfaz Modificar Laboratorio
            modificarEmpaque.ObtenerLaboratoriModificar(new ImagenesProducto(id, nombImg, 
                        imagen, principal, estatus, producto));

            this.mainPrincipal.getworkSpace().add(modificarEmpaque, BorderLayout.CENTER);
            this.mainPrincipal.getworkSpace().revalidate();
            this.mainPrincipal.getworkSpace().repaint();
        }
    }//GEN-LAST:event_jTableMImgProMouseClicked

    private void buscarMImgProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMImgProMouseClicked
        if (buscartxtMImgPro.getText() == "" || buscartxtMImgPro.getText() == null) {
            JOptionPane.showMessageDialog(null, "Debes escribir algo para filtrar...",
                    "Mensaje", JOptionPane.WARNING_MESSAGE);
        } else {
            LinkedList<ImagenesProducto> cat = new DAOImagenesProductoImp().consultaInd(buscartxtMImgPro.getText());
            Object listaDatos[][] = new Object[cat.size()][10];
            for (int i = 0; i < cat.size(); i++) {
                listaDatos[i][0] = cat.get(i).getIdImagen();
                listaDatos[i][1] = cat.get(i).getNombreImagen();
                listaDatos[i][2] = cat.get(i).getImagen();
                listaDatos[i][3] = cat.get(i).getPrincipal();
                listaDatos[i][4] = cat.get(i).getEstatus();
                listaDatos[i][5] = cat.get(i).getIdProducto();
            }

            DefaultTableModel modelTable = new DefaultTableModel(
                    listaDatos,
                    new Object[]{"ID", "NOMBIMAGEN", "IMAGEN",
                        "PRINCIPAL", "ESTATUS", "IDPRODUCTO"}) {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            this.jTableMImgPro.setModel(modelTable);
            this.jTableMImgPro.getColumnModel().getColumn(0).setMinWidth(10);
            this.jTableMImgPro.getColumnModel().getColumn(0).setMaxWidth(50);

            this.jTableMImgPro.getColumnModel().getColumn(1).setMinWidth(50);
            this.jTableMImgPro.getColumnModel().getColumn(1).setMaxWidth(350);

            this.jTableMImgPro.getColumnModel().getColumn(2).setMinWidth(50);
            this.jTableMImgPro.getColumnModel().getColumn(2).setMaxWidth(350);

            this.jTableMImgPro.getColumnModel().getColumn(3).setMinWidth(10);
            this.jTableMImgPro.getColumnModel().getColumn(3).setMaxWidth(200);

            this.jTableMImgPro.getColumnModel().getColumn(4).setMinWidth(10);
            this.jTableMImgPro.getColumnModel().getColumn(4).setMaxWidth(200);

            this.jTableMImgPro.getColumnModel().getColumn(5).setMinWidth(10);
            this.jTableMImgPro.getColumnModel().getColumn(5).setMaxWidth(200);



        }

    }//GEN-LAST:event_buscarMImgProMouseClicked

    private void previewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewMouseClicked
        if (cambioPagina == 1) {
            preview.setVisible(false);
            next.setVisible(true);
            leyenda.setVisible(true);
            MostrarDatosPedidoDetalle();
        } else {
            next.setVisible(true);
            cambioPagina--;
            MostrarDatosPedidoDetalle();
            leyenda.setVisible(false);

        }
    }//GEN-LAST:event_previewMouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        if (cambioPagina >= ContRegistro) {
            next.setVisible(false);
            preview.setVisible(true);
            leyenda.setVisible(true);
            MostrarDatosPedidoDetalle();
        } else {
            cambioPagina++;
            preview.setVisible(true);
            MostrarDatosPedidoDetalle();
            leyenda.setVisible(false);
        }
    }//GEN-LAST:event_nextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarMImgPro;
    private javax.swing.JTextField buscartxtMImgPro;
    private javax.swing.JLabel cancelarMImgPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMImgPro;
    private javax.swing.JLabel leyenda;
    private javax.swing.JPanel mainMostrarPro;
    private javax.swing.JButton next;
    private javax.swing.JLabel nuevoMImgPro;
    private javax.swing.JPanel opcionesMostrarEmp;
    private javax.swing.JPanel opcionesMostrarLab3;
    private javax.swing.JButton preview;
    private javax.swing.JLabel segmentacion;
    // End of variables declaration//GEN-END:variables
    private Main mainPrincipal;

}
