package Vista.Sucursales;

import Vistas.Categorias.*;
import java.awt.BorderLayout;
import DAOs.*;
import javax.swing.table.DefaultTableModel;
import MainPrincipal.Main;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author 52351
 */
public class mostrarSucursales extends javax.swing.JPanel {

    /**
     * Creates new form mostrarLaboratorios
     */
    public void setMostrarSucursales(Main workspace) {
        mainPrincipal = workspace;
    }

    public mostrarSucursales() {
        initComponents();
        leyenda.setVisible(false);
        ContRegistro = new DAOSucursalesImp().contRegistros();
        ContRegistro = Math.ceil((ContRegistro / 10));
    }

    private Main mainPrincipal;
    private double ContRegistro;
    private int cambioPagina = 1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        mainMostrarSuc = new javax.swing.JPanel();
        tablaMostrarSuc = new javax.swing.JScrollPane();
        jTableMS = new javax.swing.JTable();
        opcionesMostrarSuc = new javax.swing.JPanel();
        nuevaSuc = new javax.swing.JLabel();
        cancelarMS = new javax.swing.JLabel();
        buscartxtMS = new javax.swing.JTextField();
        buscarMS = new javax.swing.JLabel();
        opcionesMostrarEmp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        segmentacion = new javax.swing.JLabel();
        preview = new javax.swing.JButton();
        next = new javax.swing.JButton();
        leyenda = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(228, 225, 225));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true), "Mostrar sucursales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        mainMostrarSuc.setBackground(new java.awt.Color(233, 231, 231));

        tablaMostrarSuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMostrarSucMouseClicked(evt);
            }
        });

        jTableMS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "TELEFONO", "DIRECCIÓN", "COLINIA", "CP", "PRESUPUESTO", "ESTATUS", "CIUDAD"
            }
        ));
        jTableMS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMSMouseClicked(evt);
            }
        });
        tablaMostrarSuc.setViewportView(jTableMS);

        opcionesMostrarSuc.setBackground(new java.awt.Color(48, 45, 45));

        nuevaSuc.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        nuevaSuc.setForeground(new java.awt.Color(255, 255, 255));
        nuevaSuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        nuevaSuc.setText("NUEVA SURCUSAL");
        nuevaSuc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        nuevaSuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevaSuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevaSucMouseClicked(evt);
            }
        });

        cancelarMS.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        cancelarMS.setForeground(new java.awt.Color(255, 255, 255));
        cancelarMS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        cancelarMS.setText("CANCELAR");
        cancelarMS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        cancelarMS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarMS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesMostrarSucLayout = new javax.swing.GroupLayout(opcionesMostrarSuc);
        opcionesMostrarSuc.setLayout(opcionesMostrarSucLayout);
        opcionesMostrarSucLayout.setHorizontalGroup(
            opcionesMostrarSucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesMostrarSucLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(nuevaSuc, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarMS, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        opcionesMostrarSucLayout.setVerticalGroup(
            opcionesMostrarSucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarSucLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(opcionesMostrarSucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarMS)
                    .addComponent(nuevaSuc))
                .addGap(19, 19, 19))
        );

        buscarMS.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        buscarMS.setForeground(new java.awt.Color(102, 102, 102));
        buscarMS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/most.png"))); // NOI18N
        buscarMS.setText("BUSCAR SURCUSAL");
        buscarMS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        buscarMS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarMS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMSMouseClicked(evt);
            }
        });

        opcionesMostrarEmp.setBackground(java.awt.Color.lightGray);

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Cambio pagina cada página contiene 10 registros.");

        segmentacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        preview.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N
        preview.setText("Anterior");
        preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewMouseClicked(evt);
            }
        });

        next.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha.png"))); // NOI18N
        next.setText("Siguiente");
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesMostrarEmpLayout = new javax.swing.GroupLayout(opcionesMostrarEmp);
        opcionesMostrarEmp.setLayout(opcionesMostrarEmpLayout);
        opcionesMostrarEmpLayout.setHorizontalGroup(
            opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(next)
                .addGap(187, 187, 187))
            .addGroup(opcionesMostrarEmpLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opcionesMostrarEmpLayout.setVerticalGroup(
            opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarEmpLayout.createSequentialGroup()
                .addGroup(opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(next)
                    .addGroup(opcionesMostrarEmpLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(opcionesMostrarEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(opcionesMostrarEmpLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(preview))
                            .addGroup(opcionesMostrarEmpLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        leyenda.setBackground(new java.awt.Color(255, 0, 51));
        leyenda.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(255, 51, 51));
        leyenda.setText("No se encuentran mas registros en paginas.");

        javax.swing.GroupLayout mainMostrarSucLayout = new javax.swing.GroupLayout(mainMostrarSuc);
        mainMostrarSuc.setLayout(mainMostrarSucLayout);
        mainMostrarSucLayout.setHorizontalGroup(
            mainMostrarSucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMostrarSucLayout.createSequentialGroup()
                .addGroup(mainMostrarSucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMostrarSucLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainMostrarSucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tablaMostrarSuc)
                            .addComponent(opcionesMostrarSuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMostrarSucLayout.createSequentialGroup()
                                .addGap(0, 192, Short.MAX_VALUE)
                                .addComponent(buscartxtMS, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarMS, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainMostrarSucLayout.createSequentialGroup()
                        .addGroup(mainMostrarSucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainMostrarSucLayout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(leyenda))
                            .addGroup(mainMostrarSucLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(opcionesMostrarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainMostrarSucLayout.setVerticalGroup(
            mainMostrarSucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMostrarSucLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMostrarSucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarMS)
                    .addComponent(buscartxtMS, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tablaMostrarSuc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcionesMostrarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leyenda)
                .addGap(18, 18, 18)
                .addComponent(opcionesMostrarSuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(mainMostrarSuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainMostrarSuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Mostrar Categorias");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaSucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaSucMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        agregarSucursal nuevaSuc = new agregarSucursal();
        nuevaSuc.setSize(mainPrincipal.getworkSpace().getSize());
        nuevaSuc.setVisible(true);
        nuevaSuc.setMain(mainPrincipal);

        mainPrincipal.getworkSpace().add(nuevaSuc, BorderLayout.CENTER);
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();


    }//GEN-LAST:event_nuevaSucMouseClicked

    private void cancelarMSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMSMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();
    }//GEN-LAST:event_cancelarMSMouseClicked

    private void jTableMSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMSMouseClicked
        int row;
        row = jTableMS.getSelectedRow();

        //Verificamos que el evento este en el rango de la tabla.
        if (row > -1 && row <= jTableMS.getSelectedRow()) {
            //creamos la ventana modificar
            modificarSucursal modificarSuc = new modificarSucursal();
            this.mainPrincipal.getworkSpace().removeAll();
            modificarSuc.setSize(mainPrincipal.getworkSpace().getSize());
            modificarSuc.setVisible(true);
            modificarSuc.setMainPrincipal(mainPrincipal);
            //Datos de la tabla, selecionar un row
            int id = Integer.parseInt(String.valueOf(this.jTableMS.getValueAt(row, 0)));
            String nombre = String.valueOf(this.jTableMS.getValueAt(row, 1));
            String telefono = String.valueOf(this.jTableMS.getValueAt(row, 2));
            String direccion = String.valueOf(this.jTableMS.getValueAt(row, 3));
            String colonia = String.valueOf(this.jTableMS.getValueAt(row, 4));
            String cp = String.valueOf(this.jTableMS.getValueAt(row, 5));
            float presupuesto = Float.parseFloat(String.valueOf(this.jTableMS.getValueAt(row, 6)));
            char estatus = String.valueOf(this.jTableMS.getValueAt(row, 7)).charAt(0);
            String ciudad = String.valueOf(this.jTableMS.getValueAt(row, 8));
            //Ingresan los datos de la tabla a la interfaz Modificar Laboratorio
            modificarSuc.ObtenerLaboratoriModificar(new Sucursales
        (id, nombre, telefono, direccion, colonia, colonia, presupuesto, estatus, ciudad));

            this.mainPrincipal.getworkSpace().add(modificarSuc, BorderLayout.CENTER);
            this.mainPrincipal.getworkSpace().revalidate();
            this.mainPrincipal.getworkSpace().repaint();
        }
    }//GEN-LAST:event_jTableMSMouseClicked

    private void buscarMSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMSMouseClicked
        if (buscartxtMS.getText().equals("")  || buscartxtMS.getText() == null) {
            JOptionPane.showMessageDialog(null, "Debes escribir algo para filtrar...",
                    "Mensaje", JOptionPane.WARNING_MESSAGE);
        } else {
            LinkedList<Sucursales> suc = new DAOSucursalesImp().consultaInd(buscartxtMS.getText());
            if(suc != null){
            Object listaDatos[][] = new Object[suc.size()][9];
            for (int i = 0; i < suc.size(); i++) {
                listaDatos[i][0] = suc.get(i).getIdSucursal();
                listaDatos[i][1] = suc.get(i).getNombre();
                listaDatos[i][2] = suc.get(i).getTelefono();
                listaDatos[i][3] = suc.get(i).getDireccion();
                listaDatos[i][4] = suc.get(i).getColonia();
                listaDatos[i][5] = suc.get(i).getCodPostal();
                listaDatos[i][6] = suc.get(i).getPresupuesto();
                listaDatos[i][7] = suc.get(i).getEstatus();
                listaDatos[i][8] = suc.get(i).getCiudad();
            }

            DefaultTableModel modelTable = new DefaultTableModel(
                    listaDatos,
                    new Object[]{"ID", "NOMBRE", "TELÉFONO", "DIRECCIÓN", "COLONIA", "CP", "PRESUPUESTO", "ESTATUS", "CIUDAD"}) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            this.jTableMS.setModel(modelTable);
            this.jTableMS.getColumnModel().getColumn(0).setMaxWidth(30);
            this.jTableMS.getColumnModel().getColumn(1).setMaxWidth(300);
            this.jTableMS.getColumnModel().getColumn(2).setMaxWidth(100);
            this.jTableMS.getColumnModel().getColumn(3).setMaxWidth(400);
            this.jTableMS.getColumnModel().getColumn(4).setMaxWidth(100);
            this.jTableMS.getColumnModel().getColumn(5).setMaxWidth(70);
            this.jTableMS.getColumnModel().getColumn(6).setMaxWidth(130);
            this.jTableMS.getColumnModel().getColumn(7).setMaxWidth(100);
            this.jTableMS.getColumnModel().getColumn(8).setMaxWidth(100);

        }
        }

    }//GEN-LAST:event_buscarMSMouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        if (cambioPagina >= ContRegistro) {
            next.setVisible(false);
            leyenda.setVisible(true);
        } else {
            cambioPagina++;
            preview.setVisible(true);
            MostrarDatosSucursal();
            leyenda.setVisible(false);
        }
    }//GEN-LAST:event_nextMouseClicked

    private void previewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewMouseClicked
        if (cambioPagina == 1) {
            preview.setVisible(false);
            leyenda.setVisible(true);
        } else {
            next.setVisible(true);
            cambioPagina--;
            MostrarDatosSucursal();
            leyenda.setVisible(false);

        }
    }//GEN-LAST:event_previewMouseClicked

    private void tablaMostrarSucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMostrarSucMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMostrarSucMouseClicked

    public void MostrarDatosSucursal() {
        LinkedList<Sucursales> suc = new DAOSucursalesImp().show(cambioPagina);
        if (ContRegistro <= 0) {
            next.setVisible(false);
            preview.setVisible(false);
            return;
        } else {
            next.setVisible(true);
            preview.setVisible(true);
            this.segmentacion.setText("Página " + cambioPagina + " de " + (int) ContRegistro + " Páginas en total");
            Object listaDatos[][] = new Object[suc.size()][9];
            for (int i = 0; i < suc.size(); i++) {
                listaDatos[i][0] = suc.get(i).getIdSucursal();
                listaDatos[i][1] = suc.get(i).getNombre();
                listaDatos[i][2] = suc.get(i).getTelefono();
                listaDatos[i][3] = suc.get(i).getDireccion();
                listaDatos[i][4] = suc.get(i).getColonia();
                listaDatos[i][5] = suc.get(i).getCodPostal();
                listaDatos[i][6] = suc.get(i).getPresupuesto();
                listaDatos[i][7] = suc.get(i).getEstatus();
                listaDatos[i][8] = suc.get(i).getCiudad();
            }

            DefaultTableModel modelTable = new DefaultTableModel(
                    listaDatos,
                    new Object[]{"ID", "NOMBRE", "TELÉFONO", "DIRECCIÓN", "COLONIA", "CP", "PRESUPUESTO", "ESTATUS", "CIUDAD"}) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            this.jTableMS.setModel(modelTable);
            this.jTableMS.getColumnModel().getColumn(0).setMaxWidth(30);
            this.jTableMS.getColumnModel().getColumn(1).setMaxWidth(300);
            this.jTableMS.getColumnModel().getColumn(2).setMaxWidth(100);
            this.jTableMS.getColumnModel().getColumn(3).setMaxWidth(400);
            this.jTableMS.getColumnModel().getColumn(4).setMaxWidth(100);
            this.jTableMS.getColumnModel().getColumn(5).setMaxWidth(70);
            this.jTableMS.getColumnModel().getColumn(6).setMaxWidth(130);
            this.jTableMS.getColumnModel().getColumn(7).setMaxWidth(100);
            this.jTableMS.getColumnModel().getColumn(8).setMaxWidth(100);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarMS;
    private javax.swing.JTextField buscartxtMS;
    private javax.swing.JLabel cancelarMS;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTableMS;
    private javax.swing.JLabel leyenda;
    private javax.swing.JPanel mainMostrarSuc;
    private javax.swing.JButton next;
    private javax.swing.JLabel nuevaSuc;
    private javax.swing.JPanel opcionesMostrarEmp;
    private javax.swing.JPanel opcionesMostrarSuc;
    private javax.swing.JButton preview;
    private javax.swing.JLabel segmentacion;
    private javax.swing.JScrollPane tablaMostrarSuc;
    // End of variables declaration//GEN-END:variables
}
