package Vista.Pedidos;

import java.awt.BorderLayout;
import DAOs.DAOPedidosImp;
import DAOs.Laboratorios;
import DAOs.Pedidos;
import javax.swing.table.DefaultTableModel;
import MainPrincipal.Main;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 52351
 */
public class mostrarPedidos extends javax.swing.JPanel {

    /**
     * Creates new form mostrarPedidos
     */
    public void setMostrarPedidos(Main workspace) {
        mainPrincipal = workspace;
    }

    public mostrarPedidos() {
        initComponents();
        ContRegistro = new DAOPedidosImp().contarRegistros();
        ContRegistro = Math.ceil((ContRegistro / 10));
        contRegistroPagado = new DAOPedidosImp().contarRegistroPagados();
        contRegistroPagado = Math.ceil(contRegistroPagado / 10);
        System.out.println(ContRegistro);
        leyenda.setVisible(false);

    }

    private Main mainPrincipal;
    private double ContRegistro;
    private double contRegistroPagado;
    private int cambioPagina = 1;
    private int cambioPagina2 = 1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<String>();
        mainMostrarLab = new javax.swing.JPanel();
        tablaMostrarLab = new javax.swing.JScrollPane();
        jTableML = new javax.swing.JTable();
        opcionesMostrarLab = new javax.swing.JPanel();
        nuevolabML = new javax.swing.JLabel();
        cancelarML = new javax.swing.JLabel();
        buscartxtML = new javax.swing.JTextField();
        buscarML = new javax.swing.JLabel();
        opcionesMostrarLab3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        segmentacion = new javax.swing.JLabel();
        preview = new javax.swing.JButton();
        next = new javax.swing.JButton();
        leyenda = new javax.swing.JLabel();
        PedidosPagados = new javax.swing.JLabel();
        PedidosPag = new javax.swing.JCheckBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(228, 225, 225));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true), "Mostrar pedidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        mainMostrarLab.setBackground(new java.awt.Color(233, 231, 231));

        jTableML.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "FECHA DE REGISTRO", "FECHA RECEPCIÓN", "TOTAL A PAGAR", "CANT. PAGADA", "ESTATUS", "PROVEDOR", "SUCURSAL", "EMPLEADO"
            }
        ));
        jTableML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMLMouseClicked(evt);
            }
        });
        tablaMostrarLab.setViewportView(jTableML);

        opcionesMostrarLab.setBackground(new java.awt.Color(48, 45, 45));

        nuevolabML.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        nuevolabML.setForeground(new java.awt.Color(255, 255, 255));
        nuevolabML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        nuevolabML.setText("NUEVO PEDIDO");
        nuevolabML.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        nuevolabML.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevolabML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevolabMLMouseClicked(evt);
            }
        });

        cancelarML.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        cancelarML.setForeground(new java.awt.Color(255, 255, 255));
        cancelarML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        cancelarML.setText("CANCELAR");
        cancelarML.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        cancelarML.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesMostrarLabLayout = new javax.swing.GroupLayout(opcionesMostrarLab);
        opcionesMostrarLab.setLayout(opcionesMostrarLabLayout);
        opcionesMostrarLabLayout.setHorizontalGroup(
            opcionesMostrarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesMostrarLabLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(nuevolabML, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addComponent(cancelarML, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        opcionesMostrarLabLayout.setVerticalGroup(
            opcionesMostrarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarLabLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(opcionesMostrarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevolabML)
                    .addComponent(cancelarML))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        buscarML.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        buscarML.setForeground(new java.awt.Color(102, 102, 102));
        buscarML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/most.png"))); // NOI18N
        buscarML.setText("BUSCAR PEDIDO");
        buscarML.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        buscarML.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMLMouseClicked(evt);
            }
        });

        opcionesMostrarLab3.setBackground(java.awt.Color.lightGray);

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Cambio pagina \"cada página contiene 10 registros.");

        segmentacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        preview.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regreso.png"))); // NOI18N
        preview.setText("Anterior");
        preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewMouseClicked(evt);
            }
        });

        next.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha.png"))); // NOI18N
        next.setText("Siguiente");
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout opcionesMostrarLab3Layout = new javax.swing.GroupLayout(opcionesMostrarLab3);
        opcionesMostrarLab3.setLayout(opcionesMostrarLab3Layout);
        opcionesMostrarLab3Layout.setHorizontalGroup(
            opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(next)
                .addGap(163, 163, 163))
            .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opcionesMostrarLab3Layout.setVerticalGroup(
            opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                .addGroup(opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(next)
                    .addGroup(opcionesMostrarLab3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(opcionesMostrarLab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(preview))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        leyenda.setBackground(new java.awt.Color(255, 0, 51));
        leyenda.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(255, 51, 51));
        leyenda.setText("No se encuentran mas registros en paginas.");

        PedidosPagados.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        PedidosPagados.setForeground(new java.awt.Color(255, 255, 255));
        PedidosPagados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orden.png"))); // NOI18N
        PedidosPagados.setText("PEDIDOS PAGADOS");
        PedidosPagados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        PedidosPagados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PedidosPagados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PedidosPagadosMouseClicked(evt);
            }
        });

        PedidosPag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PedidosPagMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainMostrarLabLayout = new javax.swing.GroupLayout(mainMostrarLab);
        mainMostrarLab.setLayout(mainMostrarLabLayout);
        mainMostrarLabLayout.setHorizontalGroup(
            mainMostrarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMostrarLabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMostrarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMostrarLabLayout.createSequentialGroup()
                        .addGroup(mainMostrarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tablaMostrarLab)
                            .addComponent(opcionesMostrarLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMostrarLabLayout.createSequentialGroup()
                                .addComponent(PedidosPagados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PedidosPag)
                                .addGap(30, 30, 30)
                                .addComponent(buscartxtML, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarML, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMostrarLabLayout.createSequentialGroup()
                        .addGap(0, 98, Short.MAX_VALUE)
                        .addComponent(opcionesMostrarLab3, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
            .addGroup(mainMostrarLabLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(leyenda)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainMostrarLabLayout.setVerticalGroup(
            mainMostrarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMostrarLabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMostrarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PedidosPag, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainMostrarLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscarML)
                        .addComponent(buscartxtML, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PedidosPagados)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tablaMostrarLab, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(opcionesMostrarLab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leyenda)
                .addGap(39, 39, 39)
                .addComponent(opcionesMostrarLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(mainMostrarLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainMostrarLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevolabMLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevolabMLMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        agregarPedido nuevoped = new agregarPedido();
        nuevoped.setSize(mainPrincipal.getworkSpace().getSize());
        nuevoped.setVisible(true);
        nuevoped.setMain(mainPrincipal);
        mainPrincipal.getworkSpace().add(nuevoped, BorderLayout.CENTER);
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();


    }//GEN-LAST:event_nuevolabMLMouseClicked

    private void cancelarMLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMLMouseClicked
        mainPrincipal.getworkSpace().removeAll();
        mainPrincipal.getworkSpace().revalidate();
        mainPrincipal.getworkSpace().repaint();
    }//GEN-LAST:event_cancelarMLMouseClicked

    /**
     * Método que funciona para detectar un evento de la tabla Laboratorios.
     *
     * @param evt evento al dar click a la tabla.
     */
    private void jTableMLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMLMouseClicked
        if (JOptionPane.showConfirmDialog(this, "Seleccione SI Para realizar un pago\n "
                + " Seleccione NO para modicar", "Procesando...", JOptionPane.INFORMATION_MESSAGE)
                == JOptionPane.YES_OPTION) {
            int row;
            row = jTableML.getSelectedRow();
            if (Float.parseFloat(String.valueOf(this.jTableML.getValueAt(row, 3)))
                    != Float.parseFloat(String.valueOf(this.jTableML.getValueAt(row, 4)))) {

                //Verificamos que el evento este en el rango de la tabla.
                if (row > -1 && row <= jTableML.getSelectedRow()) {
                    try {
                        RealizarPago pago = new RealizarPago(null, true);
                        //Datos de la tabla del renglón seleccionado
                        DateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

                        int id = Integer.parseInt(String.valueOf(this.jTableML.getValueAt(row, 0)));
                        Date fechaReg = formato.parse(String.valueOf(this.jTableML.getValueAt(row, 1)));
                        Date fechaRecp = formato.parse(String.valueOf(this.jTableML.getValueAt(row, 2)));;
                        float totalPag = Float.parseFloat(String.valueOf(this.jTableML.getValueAt(row, 3)));
                        float cantPag = Float.parseFloat(String.valueOf(this.jTableML.getValueAt(row, 4)));;

                        pago.resibirDatosPedido(new Pedidos(id, fechaReg, fechaRecp, totalPag, cantPag));
                        pago.setMain(mainPrincipal);
                        pago.setVisible(true);
                    } catch (ParseException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

        } else {
            int row;
            row = jTableML.getSelectedRow();

            //Verificamos que el evento este en el rango de la tabla.
            if (row > -1 && row <= jTableML.getSelectedRow()) {
                try {
                    //creamos la ventana modificar
                    modificarPedido modificarLab = new modificarPedido();
                    this.mainPrincipal.getworkSpace().removeAll();
                    modificarLab.setSize(mainPrincipal.getworkSpace().getSize());
                    modificarLab.setVisible(true);
                    modificarLab.setMainPrincipal(mainPrincipal);
                    //Datos de la tabla, selecionar un row
                    DateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                    
                    int id = Integer.parseInt(String.valueOf(this.jTableML.getValueAt(row, 0)));
                    Date fechaReg = formato.parse(String.valueOf(this.jTableML.getValueAt(row, 1)));
                    Date fechaRecp = formato.parse(String.valueOf(this.jTableML.getValueAt(row, 2)));
                    float totalPag = Float.parseFloat(String.valueOf(this.jTableML.getValueAt(row, 3)));
                    float cantPag = Float.parseFloat(String.valueOf(this.jTableML.getValueAt(row, 4)));
                    char estatus = String.valueOf(this.jTableML.getValueAt(row, 5)).charAt(0);
                    String proveedor = String.valueOf(this.jTableML.getValueAt(row, 6));
                    String sucursal = String.valueOf(this.jTableML.getValueAt(row, 7));
                    String empleado = String.valueOf(this.jTableML.getValueAt(row, 8));
                    //Ingresan los datos de la tabla a la interfaz Modificar Laboratorio
                    modificarLab.ObtenerDatosPedido
                    (new Pedidos(id,fechaReg, fechaRecp, totalPag, cantPag, estatus, proveedor,
                            sucursal, empleado));
                    
                    this.mainPrincipal.getworkSpace().add(modificarLab, BorderLayout.CENTER);
                    this.mainPrincipal.getworkSpace().revalidate();
                    this.mainPrincipal.getworkSpace().repaint();
                } catch (ParseException ex) {
                    Logger.getLogger(mostrarPedidos.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_jTableMLMouseClicked

    private void buscarMLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMLMouseClicked
        LinkedList<Pedidos> ped = new DAOPedidosImp().busquedaPorID(Integer.parseInt(buscartxtML.getText()));
        if (ped != null) {
            Object listaDatos[][] = new Object[ped.size()][9];
            for (int i = 0; i < ped.size(); i++) {
                listaDatos[i][0] = ped.get(i).getIdpedido();
                listaDatos[i][1] = ped.get(i).getFecharegistro();
                listaDatos[i][2] = ped.get(i).getFechaRecepcion();
                listaDatos[i][3] = ped.get(i).getTotalpagar();
                listaDatos[i][4] = ped.get(i).getCantidadpagada();
                listaDatos[i][5] = ped.get(i).getEstatus();
                listaDatos[i][6] = ped.get(i).getIdproveedor();
                listaDatos[i][7] = ped.get(i).getIdSucursal();
                listaDatos[i][8] = ped.get(i).getIdEmpleado();

            }

            DefaultTableModel modelTable = new DefaultTableModel(
                    listaDatos,
                    new Object[]{"ID", "FECHAREG", "FECHARECP", "TOTAL PAGAR",
                        "CANT.PAGADA", "ESTATUS", "PROVEEDOR", "SUCURSAL", "EMPLEADO"}) {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            this.jTableML.setModel(modelTable);
//            this.jTableML.getColumnModel().getColumn(0).setMinWidth(10);
//            this.jTableML.getColumnModel().getColumn(0).setMaxWidth(50);
//
//            this.jTableML.getColumnModel().getColumn(1).setMinWidth(50);
//            this.jTableML.getColumnModel().getColumn(1).setMaxWidth(350);
//
//            this.jTableML.getColumnModel().getColumn(2).setMinWidth(50);
//            this.jTableML.getColumnModel().getColumn(2).setMaxWidth(350);
//
//            this.jTableML.getColumnModel().getColumn(3).setMinWidth(10);
//            this.jTableML.getColumnModel().getColumn(3).setMaxWidth(200);
        }
    }//GEN-LAST:event_buscarMLMouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        if (!PedidosPag.isSelected()) {
            if (cambioPagina >= ContRegistro) {
                next.setVisible(false);
                preview.setVisible(true);
                leyenda.setVisible(true);
                MostrarDatosPedidos();
            } else {
                cambioPagina++;
                preview.setVisible(true);
                MostrarDatosPedidos();
                leyenda.setVisible(false);
            }
        } else {
            if (cambioPagina2 >= contRegistroPagado) {
                next.setVisible(false);
                preview.setVisible(true);
                leyenda.setVisible(true);
                MostrarPedidosPagados();
            } else {
                cambioPagina++;
                preview.setVisible(true);
                MostrarPedidosPagados();
                leyenda.setVisible(false);
            }
        }
    }//GEN-LAST:event_nextMouseClicked

    private void previewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewMouseClicked
        if (!PedidosPag.isSelected()) {
            if (cambioPagina == 1) {
                preview.setVisible(false);
                next.setVisible(true);
                leyenda.setVisible(true);
                MostrarDatosPedidos();
            } else {
                next.setVisible(true);
                cambioPagina--;
                MostrarDatosPedidos();
                leyenda.setVisible(false);

            }
        } else {
            if (cambioPagina2 == 1) {
                preview.setVisible(false);
                next.setVisible(true);
                leyenda.setVisible(true);
                MostrarPedidosPagados();
            } else {
                next.setVisible(true);
                cambioPagina2--;
                MostrarPedidosPagados();
                leyenda.setVisible(false);
            }
        }
    }//GEN-LAST:event_previewMouseClicked

    private void PedidosPagadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PedidosPagadosMouseClicked

    }//GEN-LAST:event_PedidosPagadosMouseClicked

    private void PedidosPagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PedidosPagMouseClicked
        MostrarPedidosPagados();

    }//GEN-LAST:event_PedidosPagMouseClicked

    private void MostrarPedidosPagados() {
        //Obtiene los registros en paginas de 10 en 10
        LinkedList<Pedidos> ped = new DAOPedidosImp().pedidosPagados(cambioPagina2);
        this.segmentacion.setText("Página " + cambioPagina2 + " de " + (int) contRegistroPagado + " Páginas en total");
        Object listaDatos[][] = new Object[ped.size()][9];
        for (int i = 0; i < ped.size(); i++) {
            listaDatos[i][0] = ped.get(i).getIdpedido();
            listaDatos[i][1] = ped.get(i).getFecharegistro().toString();
            listaDatos[i][2] = ped.get(i).getFechaRecepcion().toString();
            listaDatos[i][3] = ped.get(i).getTotalpagar();
            listaDatos[i][4] = ped.get(i).getCantidadpagada();
            listaDatos[i][5] = ped.get(i).getEstatus();
            listaDatos[i][6] = ped.get(i).getIdproveedor();
            listaDatos[i][7] = ped.get(i).getIdSucursal();
            listaDatos[i][8] = ped.get(i).getIdEmpleado();
        }

        DefaultTableModel modelTable = new DefaultTableModel(
                listaDatos,
                new Object[]{"ID", "FECHAREG", "FECHARECP", "TOTAL PAGAR",
                    "CANT.PAGADA", "ESTATUS", "PROVEEDOR", "SUCURSAL", "EMPLEADO"}) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        this.jTableML.setModel(modelTable);
    }

    public void MostrarDatosPedidos() {
        //Obtiene los registros en paginas de 10 en 10
        LinkedList<Pedidos> ped = new DAOPedidosImp().show(cambioPagina);
        this.segmentacion.setText("Página " + cambioPagina + " de " + (int) ContRegistro + " Páginas en total");
        Object listaDatos[][] = new Object[ped.size()][9];
        for (int i = 0; i < ped.size(); i++) {
            listaDatos[i][0] = ped.get(i).getIdpedido();
            listaDatos[i][1] = ped.get(i).getFecharegistro().toString();
            listaDatos[i][2] = ped.get(i).getFechaRecepcion().toString();
            listaDatos[i][3] = ped.get(i).getTotalpagar();
            listaDatos[i][4] = ped.get(i).getCantidadpagada();
            listaDatos[i][5] = ped.get(i).getEstatus();
            listaDatos[i][6] = ped.get(i).getIdproveedor();
            listaDatos[i][7] = ped.get(i).getIdSucursal();
            listaDatos[i][8] = ped.get(i).getIdEmpleado();
        }

        DefaultTableModel modelTable = new DefaultTableModel(
                listaDatos,
                new Object[]{"ID", "FECHAREG", "FECHARECP", "TOTAL PAGAR",
                    "CANT.PAGADA", "ESTATUS", "PROVEEDOR", "SUCURSAL", "EMPLEADO"}) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        this.jTableML.setModel(modelTable);
//        this.jTableML.getColumnModel().getColumn(0).setMinWidth(10);
//        this.jTableML.getColumnModel().getColumn(0).setMaxWidth(50);
//
//        this.jTableML.getColumnModel().getColumn(1).setMinWidth(50);
//        this.jTableML.getColumnModel().getColumn(1).setMaxWidth(350);
//
//        this.jTableML.getColumnModel().getColumn(2).setMinWidth(50);
//        this.jTableML.getColumnModel().getColumn(2).setMaxWidth(350);
//
//        this.jTableML.getColumnModel().getColumn(3).setMinWidth(10);
//        this.jTableML.getColumnModel().getColumn(3).setMaxWidth(200);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox PedidosPag;
    private javax.swing.JLabel PedidosPagados;
    private javax.swing.JLabel buscarML;
    private javax.swing.JTextField buscartxtML;
    private javax.swing.JLabel cancelarML;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTableML;
    private javax.swing.JLabel leyenda;
    private javax.swing.JPanel mainMostrarLab;
    private javax.swing.JButton next;
    private javax.swing.JLabel nuevolabML;
    private javax.swing.JPanel opcionesMostrarLab;
    private javax.swing.JPanel opcionesMostrarLab3;
    private javax.swing.JButton preview;
    private javax.swing.JLabel segmentacion;
    private javax.swing.JScrollPane tablaMostrarLab;
    // End of variables declaration//GEN-END:variables
}
